Cargo.lock
Cargo.toml
crates/app/src/main.rs
crates/story/src/popover_story.rs
crates/ui/Cargo.toml
crates/ui/src/popover.rs
crates/ui/src/popup_menu.rs

Change to let Popup elements open into a window, to make sure the Popup windows, panels, menus render top than the WebView.
Then we can embed wry or other webview into GPUI.
https://github.com/huacnlee/gpui-component/assets/5518/ce005456-088f-4298-bf5d-2642cf96faff
----
This is also like other software, they are also used in child window to render the menus, popups.
- https://github.com/huacnlee/gpui-component/pull/2
- https://github.com/zed-industries/zed/pull/13730

Add to support open Popover as a child window.

---

crates/story/src/dropdown_story.rs
crates/story/src/input_story.rs
crates/ui/src/dropdown.rs
crates/ui/src/input.rs
crates/ui/src/list/list.rs
crates/ui/src/styled_ext.rs

- Add `Dropdown::string_list` to use `Vec<SharedString>` to create dropdown for easy use.
- Add `input_px`, `input_py`, `input_h` trait methods to `Styled` element.

Add Small, Large size support to Input and Dropdown and let them use same height.

---

crates/story/src/input_story.rs
crates/ui/src/input.rs

Continue #27
- Fix cut and paste invalid replace range.
- Add `Shift-Home`, `Shift-End` for select to home or end.
https://github.com/user-attachments/assets/d99c56e3-5241-46e2-b3ac-f72ef962b0b5

Add overflow scroll support to Input.

---

crates/story/src/dropdown_story.rs
crates/ui/src/dropdown.rs

* Rule: use event for `Render`, use callback for `RenderOnce`

dropdown: Use event instead of callback

---

crates/story/src/webview_story.rs
crates/ui/src/input/blink_cursor.rs
crates/ui/src/lib.rs
crates/ui/src/webview.rs

It's much prefer to use `WebViewBuilder` instead of [WebView::new](https://docs.rs/wry/latest/wry/struct.WebView.html#method.new)

Update WebView to pass wry::WebView instance

---

crates/story/src/dropdown_story.rs
crates/ui/src/dropdown.rs
crates/ui/src/list/list.rs

* Remove min-height
* Provide `render_empty` for custom empty view
* Fix crash when delegate is empty

Imporve dropdown

---

crates/app/src/main.rs

When I start up *gpui-component* its nice to be able to see that application show up,
similar to the way zed editor works upon startup...

Update demo application to activate on startup

---

crates/ui/src/label.rs

Fix label text align not work

---

crates/story/src/table_story.rs
crates/ui/src/table.rs
crates/ui/src/theme.rs

- Add `border` method to enable/disable border, default: `true`.
- Update `stripe` default to false.
- Update theme to remove table head color, just use window bg like.
Closes #155

Update table to support to support toggle col selection.

---

crates/ui/src/input/input.rs

Before
https://github.com/user-attachments/assets/38ceac8e-c98d-43c7-844b-0a2fb7d416a5
After
https://github.com/user-attachments/assets/e3f9c70e-773e-4606-ad6a-021b0e7fd7c9

Set cursor width to an integer to prevent width fluctuation on low PPI devices.

---

crates/ui/src/dock/mod.rs
crates/ui/src/dock/panel.rs
crates/ui/src/dock/stack_panel.rs
crates/ui/src/dock/tab_panel.rs

This is because the `PanelEvent::ZoomIn` is called 2 times when we click the menu (I don't why, not found the source).
So just split Zoom in, Zoom out as two difference methods to avoid this.

dock: Fix panel zoom sometimes is not work. #197

---

crates/story/src/input_story.rs
crates/ui/src/colors.rs

* Fixed some color naming with shadcn style
* Input story support scroll y

Correcting shacn to shadcn to uniformly use shadcn ui names

---

crates/ui/src/checkbox.rs
crates/ui/src/time/calendar.rs

Use small size for calendar month item to fixed content overflow

---

crates/ui/src/scroll/scrollbar.rs

fix #224
1. 纵坐标的百分比是正确的，但计算 offset 时要减掉可显示区域的长度 container_size
2. 横坐标的百分比不完全正确，计算的时候需要减掉 margin_end
3. 横坐标的百分比计算 offset 时也要减掉可显示区域的长度 container_size

scrollbar: Keep the original thumb position when mouse down to dragging

---

crates/ui/src/button.rs

button: Use primary or danger color for the disable background.

---

crates/story/src/list_story.rs
crates/ui/src/list/list.rs

Add a method to the List component to render the initial state. When input is empty, you may need to render a special interface to the user. This method can be called at this point
https://github.com/user-attachments/assets/39c61bfe-4451-43f9-b0d9-8f941ebd94dd

list: Add render_initial support to List.

---

crates/ui/src/dock/invalid_panel.rs
crates/ui/src/dock/panel.rs

dock: Keep invalid panel state info avoid missing the state.

---

crates/story/src/button_story.rs
crates/ui/src/button.rs
crates/ui/src/dropdown.rs
crates/ui/src/input/input.rs
crates/ui/src/input/otp_input.rs
crates/ui/src/slider.rs
crates/ui/src/theme.rs
crates/ui/src/time/date_picker.rs

- Add shadow to Button if it enabled.

theme: Add `shadow` option to support toggle shadow for base controls, default: true.

---

crates/ui/src/table.rs

- And add `flex_shrink_0` to table head.
Fix https://github.com/huacnlee/gpui-component/issues/160

table: Render table stripe on background even there is no enough rows

---

crates/ui/src/context_menu.rs

Closes #275
https://github.com/user-attachments/assets/7061fd93-10dd-4645-8080-ec7dbb65a80e

menu: Blocking mouse move event to back view, when PopupMenu has open.

---

crates/ui/src/switch.rs

Fix https://github.com/huacnlee/gpui-component/issues/265

Deduplicate Switch animations

---

Cargo.lock
crates/ui/src/list/list.rs
crates/ui/src/scroll/scrollbar.rs
crates/ui/src/table.rs

The https://github.com/zed-industries/zed/pull/18513 has been changed the `UniformListScrollHandle` API, it provided the scroll contents size, so we not need calculate it again.

scrollbar: Update GPUI and fix scrollbar with new API.

---

crates/app/src/story_workspace.rs
crates/story/src/popup_story.rs
crates/story/src/webview_story.rs
crates/ui/src/webview.rs

Closes #324
When we create a Wry WebView, it will take the focus into the WebView. So we must care to use it, make sure no WebView create if there no need to display.
> The `ui::WebView` has implemented when we click out of the WebView to move focus back to the main window.
>
> But by my test, first render it not work will because the Render is not trigger so the click out event not listened.
Currently change just removed WebViewStory from the demo.

story: Fix invalid focus code cause PopupStory Input cannot input anything. 

---

crates/ui/src/scroll/scrollbar.rs

Let the scrollbar only display when hovering and scrolling. The effect comparison is on the left GPUI and on the right mac. I guess they used the 10th power ease-in function, and the effect is similar.
Fixes https://github.com/huacnlee/gpui-component/issues/260

scrollbar: Do not show scrollbar event mouse is in Element rect, only show when hovered on scrollbar area or scrolled

---

crates/ui/src/dock/dock.rs
crates/ui/src/dock/tab_panel.rs

panel: Always not show active tab style, when the dock is collapsed.

---

crates/ui/src/dropdown.rs

dropdown: Use difference chevron icon color for enabled/disabled dropdown.

---

crates/ui/src/dock/tab_panel.rs

dock: Disallow move panel when it is zoomed in.

---

crates/ui/src/resizable/panel.rs

Optimization of https://github.com/longbridgeapp/gpui-component/pull/329
The issue with the initial width of the Panel has been optimised to ensure that the left side of a Panel combination like [Some(px(510.)), None] is initially rendered with a width of 510px.

resizable: Fix the bug for parent groups when initializing Panels with sizes Some and None

---

crates/story/src/table_story.rs
crates/ui/src/table.rs

As discussed in #359 adds a `AppContext` argument to the `table::TableDelegate::rows_count` method

table: Add `cx` argument to TableDelegate methods.

---

crates/ui/src/resizable/panel.rs

This solves a bug when dumping and reloading layout JSON of resizable Panels

resizable: Fix the edge case of initializing Panels with zero initial_size

---

crates/ui/src/theme.rs
crates/ui/src/title_bar.rs

Use same name rule as other theme variables.

theme: Rename `title_bar_background` to `title_bar`.

---

crates/ui/src/svg_img.rs

svg_img: Fix the conversion error of the SVG fill color with alpha

---

crates/ui/src/dock/mod.rs
crates/ui/src/dock/tab_panel.rs

But still allow to resize panels.

dock: Add `set_locked` to lock dock area to limit split, move panels.

---

crates/app/src/story_workspace.rs
crates/ui/src/dock/mod.rs
crates/ui/src/dock/panel.rs
crates/ui/src/dock/tab_panel.rs

Close #441 
```rs
DockArea::new(MAIN_DOCK_AREA.id, Some(MAIN_DOCK_AREA.version), cx).panel_style(PanelStyle::TabBar)
```

dock: Add `panel_style` to support always show TabBar.

---

crates/ui/src/dock/tab_panel.rs

panel: Fix toggle button border overlap with first tab.

---

crates/app/src/story_workspace.rs
crates/ui/src/dock/mod.rs
crates/ui/src/dock/stack_panel.rs

- Rename `set_root` to `set_center`.

dock: Fix some panel cannot able to split

---

crates/app/src/story_workspace.rs
crates/ui/src/dock/dock.rs
crates/ui/src/dock/mod.rs

**Description**:
Improve the flexibility of `DockArea`, sometime user won't need a `TabPanel`, just display some message or UI elements. Curren implement only allow use Tab or Split. So this PR will add `Plain` to `DockItem`, user can put anything which implement `PanelView` trait.
**Usage**:
```rust
let left_panels = DockItem::panel(Arc::new(<- PanelView ->));
_ = dock_area.update(cx, |view, cx| {
view.set_version(DOCK_AREA.version, cx);
view.set_left_dock(left_panels, Some(px(260.)), true, cx);
view.set_center(dock_item, cx);
view.set_dock_collapsible(
Edges {
left: false,
..Default::default()
},
cx,
);
});
```
**Screenshot**

dock: Add DockItem::panel

---

crates/ui/src/table.rs

table: Add a theme color to fixed the drag column in dark mode text style

---

crates/story/src/lib.rs
crates/ui/src/scroll/scrollbar.rs

- Move prepare code to `prepaint` stage.
Close #474

scrollbar: Use default cursor style when hovered on scrollbar.

---

crates/app/src/story_workspace.rs
crates/ui/src/input/input.rs
crates/ui/src/scroll/scrollbar.rs
crates/ui/src/theme.rs

- Only show scroll when recent scrolled.
- Keep showing scrollbar when is visible and hovered on.
- Delay 3s to fade out.
- If not visible, do not handle mouse down event.
- Add `cx.theme().scrollbar_show` option to control scrollbar show `[Hover, Scrolling]`, default: `Scrolling`.
Close #472

scrollbar: Improve scrollbar behaviour.

---

crates/story/src/table_story.rs
crates/ui/src/lib.rs
crates/ui/src/table.rs
crates/ui/src/table_row.rs

This change to make Table to only render visible range columns.
With the example table story case:
- 32 columns
- Normally fast scroll: 80~90 FPS
- Drag fast scroll: 60 FPS
- Normally fast scroll: 120 FPS
- Drag fast scroll: 90~100 FPS

table: Improve Table to only render visible range columns for performance up to stable on 120 FPS

---

crates/ui/src/dock/dock.rs
crates/ui/src/dock/mod.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/tab/tab.rs

Close #488
- Fix `collapsed` sync to `TabPanel` when load state.

panel: Avoid render panel when TabPanel is collapsed.

---

crates/ui/src/styled.rs

- Adjust `/// Set to Size::Medium` to `/// Set to Size::Large`
- Add size `.medium()`

fix: wrong size variant in sizable trait

---

crates/story/src/scrollable_story.rs
crates/ui/src/lib.rs
crates/ui/src/table.rs
crates/ui/src/virtual_list.rs

Vistual List for render a large number of differently sized rows/columns.
> NOTE: This must ensure each column width or row height.
Unlike the `uniform_list`, the each item can have different size. This is useful for more complex layout, for example, a table with different row height.

virtual_list: Add VirtualList

---

Cargo.lock
crates/story/src/list_story.rs
crates/story/src/main.rs
crates/story/src/popup_story.rs
crates/ui/src/color_picker.rs
crates/ui/src/context_menu.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/dropdown.rs
crates/ui/src/list/list.rs
crates/ui/src/popover.rs
crates/ui/src/popup_menu.rs
crates/ui/src/virtual_list.rs

Ref https://github.com/zed-industries/zed/pull/22119

chore: Update GPUI with AnchorCorner renamed to Corner.

---

crates/story/src/button_story.rs
crates/story/src/input_story.rs
crates/story/src/lib.rs
crates/story/src/main.rs
crates/story/src/table_story.rs
crates/ui/src/dock/dock.rs
crates/ui/src/dock/panel.rs
crates/ui/src/dock/stack_panel.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/resizable/panel.rs

Closes #502 #499 
- Add `visible` method to `Panel` trait, if return false this panel will disappear.
- Renamed `closeable` to `closable`.
- The `title_style`, `closable`, `zoomable` in `Panel` trait have been change `cx: &WindowContext` to `cx: &AppContext`.

dock: Add `visible` method to Panel trait to control panel visible.

---

crates/story/src/lib.rs
crates/ui/src/dock/panel.rs
crates/ui/src/dock/tab_panel.rs

The `toolbar_buttons` trait method in Panel has been changed:
```diff
- fn toolbar_buttons(&self, cx: &WindowContext) -> Vec<Button>
+ fn toolbar_buttons(&self, cx: &mut ViewContext<Self>) -> Option<Vec<Button>>
```

panel: Update Panel `toolbar_buttons` method to use ViewContext<Self>.

---

crates/ui/src/table.rs

This will make scrollbar always stay on top, even there have other element cover it.

table: Revert deferred render scrollbr for table.

---

crates/ui/src/styled.rs
crates/ui/src/table.rs

Ref #513 #542 
Add this to ability to render some custom view on top of the table, but below of the scrollbar.
- table: Renamed `scrollbar_state` to `vertical_scrollbar_state`.
- table: Removed `scroll_handle` and `horizontal_scroll_handle` method, there have a pub `vertical_scroll_handle` and `horizontal_scroll_handle` prop.

table: Add `scrollbar_visible` to Table for control the scrollbar visibility.

---

crates/ui/src/list/list.rs

- Renamed list `enable_scrollbar` to `scrollbar_visible` to match with the table API.

list: Allow disabling List selection.

---

crates/story/src/list_story.rs
crates/story/src/modal_story.rs
crates/ui/src/dropdown.rs
crates/ui/src/list/list.rs

- Add `ListEvent` and emit event for List with `Select`, `Confirm`, `Cancel` events.
- Removed useless `ListDelegate::confirmed_index` method.
- Updated `ListDelegate::confirm` method, to change `ix: Option<usize>` to `ix: usize`.

list: Add `ListEvent` to List.

---

Cargo.lock
Cargo.toml
crates/story/src/modal_story.rs
crates/ui/Cargo.toml
crates/ui/locales/ui.yml
crates/ui/src/modal.rs
crates/ui/src/root.rs

- Added `overlay_closable` method to Modal to control overlay click to close modal.
- Added `on_ok`, `on_cancel` callback method.
- Added `confirm` to setup to use default confirm style (With a Ok, Cancel button).
- The `footer` method has been changed to with a fn not a element.

modal: Add `confirm` Modal with default Ok, Cancel buttons.

---

crates/story/src/list_story.rs
crates/story/src/table_story.rs
crates/ui/src/list/list.rs
crates/ui/src/table.rs

- Add `loading` method to `ListDelegate` and `TableDelegate` to control loading view display.
- Remove `loading`, `set_loading` method from List and Table, use `loading` method in delegate instead.

list, table: Refactor to control `loading` by use delegate.

---

crates/ui/src/dock/tab_panel.rs

dock: Fix the tab panel cannot fill the entire height

---

crates/ui/src/input/input.rs

Ref: https://github.com/zed-industries/zed/pull/23603
---
Here still have a little bug in multiple lines and soft wrapped line.
Only the first line can get correct position, the wrapped line is always got the offset +1, so the first char of that soft wrapped line, we can't position the cursor at the first.

input: Fix to position cursor at correct offset on mouse down or select.

---

crates/ui/src/input/element.rs
crates/ui/src/theme.rs

- 1px width.
- Add `cx.theme.carret` variable for color and default use foreground color.
- Reduce height to match with font size.
https://github.com/user-attachments/assets/d16a51eb-2c9a-4586-8b0d-67922a738002

input: Update `carret` style.

---

crates/ui/src/input/element.rs

input: Fix Input to vertical center the mask chars.

---

crates/story/src/button_story.rs
crates/story/src/form_story.rs
crates/story/src/input_story.rs
crates/story/src/sidebar_story.rs
crates/story/src/table_story.rs
crates/story/src/title_bar.rs
crates/ui/src/input/number_input.rs
crates/ui/src/lib.rs
crates/ui/src/prelude.rs

This is useless, we can just use `gpui::prelude`, so I removed it.
- The `ui::prelude` has been removed, you can replace by use `gpui::prelude`.

chore: Remove reexport prelude.

---

crates/ui/src/table.rs

```
thread 'main' panicked at gpui-component-f2cfc37a601d48ab/dffb419/crates/ui/src/[table.rs:1562](http://table.rs:1562/):45:
attempt to subtract with overflow
stack backtrace:
```

table: Fix Table subtract with overflow error.

---

crates/ui/src/color_picker.rs

1. `cargo run` to run dashboard
2. Click `color-picker` button to open its layer and try to click same button again, to close the layer. The layer won't close. It will close only by clicking outside or selecting a color.
Move `on_mouse_up_out` handler from inner to upper child to **avoid** a race condition by changing value of `self.open` twice in `on_escape` AND `toggle_picker`.

color_picker Fix popup does not close by clicking color button again.

---

README.md
crates/ui/src/dock/dock.rs
crates/ui/src/dock/tab_panel.rs

This reverts commit 2479fc34182ddd989a6e0dc6358df18428c3d714.
> NOTE: When we enabled this, we need make sure call `cx.nofity()` when the data has been updated.
In real world application, this may reduce about 3% CPU cost.
> I watched this data about 5 minutes, the CPU cost is always like this.

Revert "dock: Revert `AnyView` cached (#607)"

---

crates/ui/src/dock/tab_panel.rs

dock: Leave some space between the tabs title and panel

---

crates/story/examples/text.rs
crates/ui/src/label.rs

And add `text` example:
```bash
cargo run --example text
```

label: Avoid string alloc and remove custom text-align.

---

crates/ui/src/dock/tiles.rs
crates/ui/src/theme.rs

- Adjust `tile_grid_size` default to `8px`.
- Fix unexpected scroll size by `-1px` design.

tiles: Limit panel x to out of bounds, but keep retaining 64px.

---

crates/ui/src/dropdown.rs
crates/ui/src/input/input.rs
crates/ui/src/input/number_input.rs
crates/ui/src/styled.rs
crates/ui/src/time/date_picker.rs

This change to avoid conflict with `outline` method in Button.
- The `outline` method in `StyledExt` now renamed to `focused_border`.

chore: Rename `outline` styled method to `focused_border`.

---

crates/ui/src/dock/tab_panel.rs

And use `selected` style for zoom button when zoomed:

panel: Reduce tool buttons gap from 8px to 4px.

---

crates/ui/src/text/element.rs

To avoid trigger parent element, for example as a Label for checkbox.

text_view: Stop propagation on click link in TextView.

---

crates/story/src/switch_story.rs
crates/ui/src/text/element.rs
crates/ui/src/text/html.rs
crates/ui/src/text/markdown.rs
crates/ui/src/text/text_view.rs

Now, we can be easy to use TextView for 1 line text.
- Removed `inline` method by previous #649 added, this is not needed.

text_view: Remove last paragraph bottom margin.

---

crates/story/src/lib.rs
crates/ui/src/dock/panel.rs

Need Update panel functions to mutable `self`, `window` and `cx`.

dock: Panel trait `set_zoomed` with mutable window and cx (#659)

---

.github/workflows/ci.yml

https://github.com/actions/runner-images/pull/11661
`cargo-machete` needs edition 2024, reopen after this PR is merged.

ci: Temporarily skip machete

---

crates/ui/src/dock/mod.rs
crates/ui/src/dock/panel.rs
crates/ui/src/dock/tiles.rs

- Limit `add_item` only allows TabPanel type.
- Export `items` method in DockArea.

tiles: Fix `active_panel` method to returns actually Panel view, avoid return TabPanel.

---

crates/story/src/calendar_story.rs
crates/ui/src/time/calendar.rs

| - | - |
| <img width="341" alt="image" src="https://github.com/user-attachments/assets/452d57b1-5ec6-4ad3-bc30-ed8a966d12e5" /> | <img width="350" alt="image" src="https://github.com/user-attachments/assets/9f664cea-aa55-479a-8d5b-61570101a66f" /> |

calendar: Differentiate text color of disabled and non-current month

---

crates/story/examples/tiles.rs
crates/ui/src/dock/mod.rs
crates/ui/src/dock/panel.rs
crates/ui/src/dock/state.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/styled.rs

- Add to support `xsmall` size for TextInput.
- Add `global`, `global_mut`, `build_panel` static method to `PanelRegistry`.

panel: Add `title_suffix` to panel and write a custom container panel example.

---

crates/story/examples/markdown.md
crates/ui/src/text/element.rs
crates/ui/src/text/text_view.rs

text_view: Add `heading_base_font_size` to TextViewStyle and fix text wrap for list item.

---

crates/story/src/tabs_story.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/tab/tab.rs
crates/ui/src/tab/tab_bar.rs

- Removed `id` argument from `TabBar::new` method.

tab: Add to support string children for TabBar.

---

crates/ui/src/button/button.rs
crates/ui/src/styled.rs
crates/ui/src/tab/tab.rs
crates/ui/src/tab/tab_bar.rs

tab: Add `xsmall`, `large` style to Tab.

---

crates/ui/src/scroll/scrollbar.rs

On `platform` level,  [should_auto_hide_scrollbars()](https://github.com/zed-industries/zed/blob/76a81607deec5b9093237cd3e98506dccc9f9565/crates/gpui/src/platform.rs#L205) might be `false` for some `platform`s, e.g. for `Linux`. 
That's why another check is needed to make scrollbars work properly on Linux.
Fixes #685

scrollbar: Fix Scrollbar not clickable when it is always showing.

---

crates/story/src/accordion_story.rs
crates/story/src/scrollable_story.rs
crates/story/src/tabs_story.rs
crates/ui/src/tab/tab.rs
crates/ui/src/tab/tab_bar.rs

- As you see on the above screenshot, the old `pill` style has been renamed to `outline`.

tab: Add new `pill` style, renamed old `pill` tab to `outline`.

---

crates/story/src/popup_story.rs
crates/ui/src/popup_menu.rs

- Added `menu_element_with_icon` and `menu_element_with_check` method to PopupMenu.
- menu: Renamed `menu_with_element` method to `menu_element`.

menu: Add `menu_element_with_icon`, `menu_element_with_check` to PopupMenu.

---

crates/ui/src/dock/tiles.rs

- Move resize handle out of the panel to avoid conflict with scrollbar.

tiles: Fix back panels flick when hover on top panel in tiles.

---

crates/ui/src/switch.rs

switch: Fix switch label to vertical center.

---

crates/story/src/tabs_story.rs
crates/ui/src/tab/tab.rs
crates/ui/src/tab/tab_bar.rs

tab: Adjust underline tab style.

---

crates/story/src/switch_story.rs
crates/ui/src/checkbox.rs
crates/ui/src/radio.rs

This change is going to solve the wrapped text line-height.
Before this change, the Label is must set `line-height: 100%` to render at same line with the checkbox.
But if there have a long text in label, wrapped lines need more line-height to leave lines spaces. But if we set line-height over the 100%, that the checkbox will not align horizontal center.
So, this change to use other child to solve this issue, we can set line-height to the child not to the label.

checkbox: Add `children` to Radio, Checkbox to display long texts.

---

crates/story/src/lib.rs
crates/story/src/main.rs
crates/story/src/modal_story.rs
crates/ui/src/dock/mod.rs
crates/ui/src/input/input.rs
crates/ui/src/root.rs

Add this to save current focused Input, this used to avoid some special keybinding conflict. 
For example: `/` as ToggleSearch, if on this action, we can check is there `has_focused_input` to decide to ignore or handle action.
- dock: Rename toggle button visible method.

dock: Rename toggle button visible method.

---

crates/story/examples/description_list.rs
crates/ui/src/description_list.rs

| - | - |
| <img width="539" alt="image" src="https://github.com/user-attachments/assets/ecd997b5-1f59-4c41-83a3-dfdee6b1be8a" /> | <img width="556" alt="image" src="https://github.com/user-attachments/assets/1088d466-1635-45c3-b578-9ada1c960d66" /> |

description_list: Fix incorrect align items for horizontal layout

---

crates/story/src/tabs_story.rs
crates/ui/src/list/list_item.rs
crates/ui/src/popup_menu.rs
crates/ui/src/tab/tab.rs
crates/ui/src/tab/tab_bar.rs

- tabs: Use default cursor when Tab is disabled.
- popup_menu: Add to support add menu item with disabled state.

tabs: Add menu to TabBar to display more items.

---

crates/story/src/modal_story.rs
crates/story/src/switch_story.rs

Ref #740
- Fix modal example button id.
- Fix switch example to allow check.

example: Fix modal example button id.

---

crates/story/src/sidebar_story.rs
crates/ui/src/sidebar/menu.rs
crates/ui/src/sidebar/mod.rs

The sidebar stopped working properly. Only one item was handling the click, by giving the ID to the `SidebarMenuItem` the issue seems to be resolved. I guess something changed within `gpui` itself that it broke.
**Before**
https://github.com/user-attachments/assets/e4fd21a9-e16d-4be6-b687-64a8a040eee7
**After**
https://github.com/user-attachments/assets/aed91762-c8ae-49f3-aaa8-77df2155f0c6

sidebar: Fix menu item click handler

---

crates/story/src/tooltip_story.rs
crates/ui/src/accordion.rs
crates/ui/src/button/button.rs
crates/ui/src/button/toggle.rs
crates/ui/src/color_picker.rs
crates/ui/src/dropdown.rs
crates/ui/src/list/list_item.rs
crates/ui/src/notification.rs
crates/ui/src/sidebar/footer.rs
crates/ui/src/sidebar/header.rs
crates/ui/src/sidebar/menu.rs
crates/ui/src/switch.rs
crates/ui/src/tab/tab.rs
crates/ui/src/table.rs
crates/ui/src/time/calendar.rs
crates/ui/src/time/date_picker.rs
crates/ui/src/title_bar.rs

This change to follow native UI to use normal cursor for all buttons, items.
Only use `pointer` for link item.

Use normal cursor for buttons.

---

crates/ui/src/dock/mod.rs
crates/ui/src/dock/stack_panel.rs
crates/ui/src/dock/tab_panel.rs

This is a continuation of #764
Without this, if we drag webview to sidebar and collapse, webview is not aware of itself being hidden

dock: Fix to sync active state to panels when collapse dock.

---

crates/story/src/modal_story.rs
crates/ui/src/modal.rs
crates/ui/src/root.rs

Fix the issue that wrongly trigger `overlay` click event for the layer-stacked `modals`.
Fix #772 
I.E. When clicking the `overlay`, only the last modal will possibly be hide(If the last modal is not `overlayClosable`, click the overlay, all the modals will not be hide).
I had tried another solution:
If this one is better than prev, I will commit it~

modal: Fix close Modal by clicking overlay to support closing layer by layer.

---

crates/story/src/sidebar_story.rs
crates/ui/src/icon.rs
crates/ui/src/sidebar/header.rs
crates/ui/src/sidebar/menu.rs
crates/ui/src/sidebar/mod.rs

Also updated the Sidebar example to support expand multiple root items.
- Sidebar create not need assign parent view_id now.

sidebar: Fix Sidebar details, something like icon size, remove view_id argument.

---

crates/ui/src/description_list.rs

| - | - |
|  <img width="752" alt="SCR-20250408-nfvl" src="https://github.com/user-attachments/assets/5ed558af-869a-4634-bbb5-80fc1481a15c" /> | <img width="752" alt="SCR-20250408-ngcy" src="https://github.com/user-attachments/assets/a5871af5-978b-421d-b608-12fa940a884c" /> |

description_list: Wrap description value if it’s too long

---

crates/story/src/modal_story.rs
crates/ui/src/input/input.rs
crates/ui/src/input/number_input.rs
crates/ui/src/list/list.rs

- Updated `set_placeholder` and `set_pattern` method to add `window` and `cx` argument.
```diff
- fn set_placeholder(&mut self, placeholder: impl Into<SharedString>)
+ fn set_placeholder(&mut self, placeholder: impl Into<SharedString>, _: &Window, cx: &mut Context<Self>)
- fn set_pattern(&mut self, pattern: regex::Regex)
+ fn set_pattern(&mut self, pattern: regex::Regex, window: &mut Window, cx: &mut Context<Self>)
```

list: Export `query_input` for support update the default Query Input.

---

Cargo.lock
script/install-linux-deps

linux: Add `libx11-xcb-dev` to install script and build error.

---

crates/story/src/webview_story.rs
crates/ui/src/input/input.rs
crates/ui/src/list/list.rs

- input: Now the `text` method `Input` changed return type from `SharedString` to `&SharedString`.
- list: Remove `set_query` and `query` method from `List`, you can use `query_input` to instead.

input: Update Input `text` method to return `&SharedString` type.

---

crates/ui/src/input/input.rs

Fix #803 changes broke Escape to dismiss dropdown menu.

input: Fix Input escape to propagate to parent element.

---

crates/ui/src/table.rs

https://github.com/user-attachments/assets/f1569eb5-e6e6-43f9-9425-0de5e2235163
Do same behavior like the macOS table.

table: Disable auto scroll when resize column out of the table right bounds.

---

Cargo.lock
crates/ui/Cargo.toml
crates/ui/src/svg_img.rs

Update SvgImg load logic and try to drop image to fix VRAM leak issue.

svg_img: No longer use the global image loader.

---

crates/story/examples/dock.rs
crates/story/src/resizable_story.rs
crates/ui/src/dock/dock.rs
crates/ui/src/dock/mod.rs
crates/ui/src/dock/stack_panel.rs
crates/ui/src/dock/state.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/resizable/panel.rs
crates/ui/tests/fixtures/layout.json

- The `Dock`, `DockItem` has changed the `size`, `sizes` to `ratio` and `ratios`, to use relative ratio instead of absolute size.

dock: Refactor to use ratio for dock, panel size.

---

crates/story/examples/dock.rs
crates/ui/src/dock/dock.rs
crates/ui/src/dock/mod.rs
crates/ui/src/dock/state.rs
crates/ui/tests/fixtures/layout.json

This change to revert `Dock` to use `Pixels` for size, not use ratio, because in most case we need to keep dock size, not wants it change when window resize, we just only want center dock to change.
The `Panel` will keep the relative size changes.

dock: Revert `dock` to use absolute size.

---

crates/story/examples/dock.rs
crates/story/src/resizable_story.rs
crates/ui/src/dock/dock.rs
crates/ui/src/dock/mod.rs
crates/ui/src/dock/stack_panel.rs
crates/ui/src/dock/state.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/resizable/panel.rs
crates/ui/tests/fixtures/layout.json

This PR to revert previous dock changes to back to use `Pixels` type for panel size.
- #833 
- #839 
- #840

dock: Revert panel `radio` size to back to use `Pixels` type for panel size.

---

crates/story/src/main.rs
crates/story/src/resizable_story.rs
crates/ui/src/dock/stack_panel.rs
crates/ui/src/resizable/mod.rs
crates/ui/src/resizable/panel.rs
crates/ui/src/sidebar/mod.rs

- The `ResizablePanelGroup` and `ResizablePanel` are changed to as stateless element, please check out the diff to migrate.

resizable: Refactor to use stateless Resizable element.

---

crates/ui/src/dropdown.rs
crates/ui/src/list/list_item.rs

This PR unifies icon parameter types in UI components:
- Changed `ListItem.check_icon` parameter type from `IconName` to `impl Into<Icon>`
- Changed `Dropdown.icon` parameter type from `impl Into<IconName>` to `impl Into<Icon>`
- Updated related rendering logic
- **API Consistency**: All components now accept the same icon parameter type
- **Backward Compatible**: Existing code using `IconName` continues to work
- **Enhanced Flexibility**: Components can now accept custom `Icon` instances directly

chore: Unify icon parameter types in ListItem and Dropdown.

---

crates/story/examples/dock.rs
crates/ui/src/dock/tab_panel.rs

And binding `Shift-Esc` for example to toggle zoom panel, `Ctrl-W` for close panel.

dock: Show keybinding for ToggleZoom menu and button.

---

crates/story/src/form_story.rs
crates/story/src/textarea_story.rs
crates/ui/src/input/element.rs
crates/ui/src/input/mod.rs
crates/ui/src/input/state.rs
crates/ui/src/input/text_input.rs
crates/ui/src/input/text_wrapper.rs

Fix #864 
Updated InputState API to split `single_line`, `multi_line` and `auto_grow`.
The `InputState::new` for default single_line, and added `multi_line` and `auto_grow` to change other mode.
https://github.com/user-attachments/assets/22a8f0d6-e264-4f39-bb30-386a41975d2b
https://github.com/user-attachments/assets/b71f0fb1-5937-470b-a278-8b1de7cfd7d7

input: Fix auto-grow height.

---

crates/story/src/number_input_story.rs
crates/ui/src/input/number_input.rs

- Number input no longer emits `InputEvent`; you need an additional subscription for `InputEvent`.

number_input: Remove `InputEvent` from `NumberInputEvent`

---

crates/ui/src/highlighter/highlight.rs
crates/ui/src/highlighter/themes/dark.tmTheme
crates/ui/src/highlighter/themes/light.tmTheme
crates/ui/src/input/code_highlighter.rs
crates/ui/src/input/element.rs
crates/ui/src/input/mod.rs
crates/ui/src/input/mode.rs
crates/ui/src/input/state.rs
crates/ui/src/text/html.rs

- Split code to lines to improve performance and cache hit rate, close #881
- Update default code highlight theme to use `macOS Classic`.

code-editor: Improve code highlight performance.

---

crates/ui/src/input/code_highlighter.rs

Again, caused by need `split('\n')` not use `.lines()`.

code-editor: Fix highlight offset on Windows.

---

crates/ui/src/input/code_highlighter.rs
crates/ui/src/input/element.rs
crates/ui/src/input/mode.rs
crates/ui/src/input/state.rs

- Fix cursor position when IME typing.
- Fix selection range when canceled IME typing.
- Fix IME popup position to follow the cursor position.
- Fix IME text to render with underline style.
Close #55

input: Fix cursor and IME popup position when IME typing.

---

crates/story/src/alert_story.rs
crates/ui/src/alert.rs
crates/ui/src/styled.rs

- The `Alert::new` method change to 2 args, first is `id`.
```diff
- fn new(message: impl Into<Text>) -> Self
+ fn new(id: impl Into<ElementId>, message: impl Into<Text>) -> Self
```

alert: Add banner mode and on_close to Alert.

---

Cargo.lock
crates/macros/Cargo.toml
crates/story/Cargo.toml
crates/story/examples/code-editor.rs
crates/story/examples/fixtures/test.nv
crates/ui/src/highlighter/highlighter.rs
crates/ui/src/highlighter/languages.rs
crates/ui/src/highlighter/registry.rs
crates/ui/src/input/element.rs
crates/ui/src/input/mode.rs
crates/ui/src/input/state.rs
crates/ui/src/text/element.rs

Add [Navi](https://navi-lang.org) language for example to external language for CodeEditor.

code-editor: Update CodeEditor to support external language.

---

crates/ui/src/dropdown.rs

Needed for a proc macro i plan to publish when ready
```rs
#[derive(Clone, DropdownItemFtl, EsFluent, EnumIter, EnumString)]
#[fluent(enumerable)]
pub enum PreferedLanguage {
English,
French,
Chinese,
}
#[derive(Clone, DropdownItemFtl, EsFluent, EnumIter, EnumString)]
#[fluent(enumerable)]
pub enum Country {
UnitedStates,
France,
China,
}
#[derive(GpuiForm)]
pub struct User {
#[gpui_form(component(input))]
pub username: Option<String>,
#[gpui_form(component(input))]
pub email: String,
#[gpui_form(component(number_input))]
pub age: Option<u32>,
#[gpui_form(component(number_input))]
pub balance: Decimal,
#[gpui_form(component(check_box))]
pub subscribe_newsletter: bool,
#[gpui_form(component(switch))]
pub enable_notifications: bool,
#[gpui_form(component(dropdown(searchable)))]
pub country: …
```

dropdown: Replace specialized impl From Vec<SharedString> to Vec<T: DropdownItem + Clone>

---

crates/story/src/radio_story.rs
crates/ui/src/radio.rs

- The `RadioGroup` now require a `id` to init.
```diff
- RadioGroup::horizontal()
+ RadioGroup::horizontal("group-id-1")
- RadioGroup::vertical()
+ RadioGroup::vertical("group-id-2")
```

radio: Add `id` to RadioGroup to avoid clicks conflict.

---

crates/ui/src/input/mode.rs
crates/ui/src/input/state.rs
crates/ui/src/input/text_wrapper.rs

- Fix to only keep indent in CodeEditor mode.
https://github.com/user-attachments/assets/4b926a18-b0b5-4419-97dd-21778cd20fb3

input: Simplify newline logic for multi-line text and fix auto-grow lines count.

---

crates/story/src/popover_story.rs
crates/ui/src/popover.rs
crates/ui/src/styled.rs

- Add `refine_style` method to `StyledExt`.
- Also improve the Popover example style.

popover: Improve PopoverContent to support styled methods.

---

crates/ui/src/input/mask_pattern.rs

Allow negative numbers and explicit positive numbers.
Added these tests:
1. Only one sign at the start of the number.
2. No signs in the middle of the number.
3. No signs in the fractional part.
4. Sign doesn't break formatting.
https://github.com/user-attachments/assets/89c4f4c7-d3bf-4cc1-aeca-7e9bedd02e20

number_input: Allow signed numbers

---

crates/story/src/input_story.rs
crates/story/src/number_input_story.rs
crates/ui/src/input/blink_cursor.rs
crates/ui/src/input/element.rs
crates/ui/src/input/number_input.rs
crates/ui/src/input/text_input.rs
crates/ui/src/styled.rs

- Fix Input, NumberInput padding x with prefix, suffix.
- Fix Input mask char to render in vertical center.
- Fix to only use `Tab`, `Shift-Tab` to indent in multi-line mode.
- Improve blink cursor to render with 1.5px width and same as line-height.

input: Fix Input prefix, suffix position, and mask `*` in vertical center.

---

crates/story/src/modal_story.rs
crates/ui/src/modal.rs

Continue #970 to add back the scrollbar to Modal again with new fixes.

modal: Add scrollbar to modal again with `scrollable` option method.

---

crates/story/examples/button.rs

The button example was not scrolling in the y direction and therefore
you were *NOT* able to see the entire ButtonStory.
This minor fix now enables one to see the entire ButtonStory.
The only code that needed to be added was
```rust
.id("button_example")
.overflow_y_scroll()
```

chore: Fix button example so that it scrolls in the y direction

---

crates/ui/src/highlighter/highlighter.rs

https://github.com/user-attachments/assets/911a4750-be80-4d1d-819b-65eb43f0f97c
https://github.com/user-attachments/assets/9e8c964d-a50e-4bf1-aede-5d712ca4fcf6

highlighter: Fix some case update will get incorrect syntax highlight.

---

crates/story/examples/fixtures/test.html
crates/story/examples/fixtures/test.md
crates/ui/src/highlighter/registry.rs
crates/ui/src/text/element.rs
crates/ui/src/text/html.rs
crates/ui/src/text/markdown.rs

- Also fixed short language name in code block, e.g.: `rs` -> `rust`.

text_view: Fix nested Blockquote render in Markdown and HTML.

---

crates/story/src/input_story.rs
crates/ui/src/input/state.rs

- Also to pub `unselect` for manually use, and fix this method will incorrect to move right 1 char.

input: Update input behaviors to do not unselect on blur or press escape.

---

crates/story/examples/code-editor.rs
crates/ui/src/input/state.rs
crates/ui/src/input/text_wrapper.rs

- Fix to emit `enter` press key in Input single-line mode.

code-editor: Add `go_to_line` method to CodeEditor.

---

crates/ui/src/progress.rs
crates/ui/src/slider.rs

This bug included since Taffy 0.8 update in [#taffy](https://github.com/zed-industries/zed/pull/34939)

chore: Fix Slider, Progress width in horizontal mode.

---

crates/story/src/list_story.rs
crates/ui/src/list/list.rs

- Add `strategy` to the `scroll_to_item` method.
```diff
+ list.scroll_to_item(selected, ScrollStrategy::Center, window, cx);
- list.scroll_to_item(selected, window, cx);
```

list: Add support for scrolling to item with the given strategy

---

crates/ui/src/dock/tab_panel.rs

dock: Adjust tab panel menu button position to align with content.

---

Cargo.lock
crates/ui/Cargo.toml
crates/ui/src/text/html.rs

To avoid depends on lightningcss, this is a heavy crate.
Ref #1132 
```
cargo bloat --release -n 200  --crates
Finished `release` profile [optimized] target(s) in 0.30s
Analyzing target/release/story
File  .text     Size Crate
4.6%  16.9%   3.4MiB lightningcss
```

chore: Use `simple-minify-html` instead of `minify-html`.

---

Cargo.lock
crates/ui/Cargo.toml
crates/ui/src/text/html.rs

Ref #1132 
This change to reduce release mode binary size from 21MB to 12MB.

chore: Use `html5minify` instead of minify-html.

---

Cargo.lock
crates/ui/Cargo.toml
crates/ui/src/text/html.rs
crates/ui/src/text/html5minify/mod.rs
crates/ui/src/text/mod.rs

Continue #1137 
Forked html5minify to improve:
- Resolve `\n` not replaced issue, now no need Regexp to replace.
- Resolve the difference version of html5ever dependency.

chore: Fork html5minify for HTML render.

---

crates/ui/src/dropdown.rs

This caused by the `bounds` of `canvas` prepaint callback now is not including the border widths.

dropdown: Fix dropdown menu width align to input width.

---

crates/story/src/modal_story.rs
crates/ui/src/modal.rs

Reverts longbridge/gpui-component#1154
By #1162 changes, this is not needed anymore.

Revert "modal: Avoid background color with alpha."

---

crates/ui/src/text/html.rs

This PR fixes an issue with parsing the styles attribute values. The main issue it fixes is that we tried splitting on `:` twice which we should only do once.
Before this change see the following variable values: 
decl="width: 10px" 
rule=["width", "10px"] (each iteration one value)
And for each rule value we tried splitting again on `:` which is wrong we should only do this once.

markdown: Fix that style attribute values are extracted correctly from img element

---

Cargo.lock
Cargo.toml
crates/ui/Cargo.toml
crates/ui/src/inspector.rs
crates/ui/src/styled.rs

Inspired by Zed, this PR implements a simple live Rust and JSON style editor for the inspector.
The rust style editor only supports `Styled` and `StyledExt` method calls with no arguments.
https://github.com/user-attachments/assets/df7f1746-92d7-416c-afd5-e389ac3ea9ae

inspector: Add live editor to inspector

---

crates/ui/src/chart/area_chart.rs
crates/ui/src/chart/bar_chart.rs
crates/ui/src/chart/line_chart.rs
crates/ui/src/plot/scale/linear.rs

- Apply linear scale based on the direction of given range.
```diff
- ScaleLinear::new(vec![1., 2., 3.], vec![0., 100.])
+ ScaleLinear::new(vec![1., 2., 3.], vec![100., 0.])
```
Currently, you can draw the linear scale from minimum to maximum or from maximum to minimum; it depends on the direction of the range.

plot: Apply linear scale based on the direction of given range

---

.gitignore
crates/ui/src/input/element.rs
crates/ui/src/input/rope_ext.rs
crates/ui/src/input/state.rs
crates/ui/src/input/text_wrapper.rs

Close #1193
Ref issue #1220 
This PR aim to shape text in visible ranges to reduce `shape_text` time for large document case.
- Fix rendering might be delayed and cause blanks when scrolling to follow the selection.
- Fix `RopeExt::lines` method to avoid call `line` method on skipped iter.

input: Improve Input performance by only shape visible lines.

---

crates/ui/src/highlighter/highlighter.rs
crates/ui/src/input/element.rs
crates/ui/src/input/mode.rs
crates/ui/src/input/state.rs
crates/ui/src/text/node.rs

Now can support up to 50K lines with code highlight.
https://github.com/user-attachments/assets/3bbba2cd-ea56-4778-b471-6beea323fbaa
----
Ref Links
- https://zed.dev/blog/syntax-aware-editing

highlighter: Improve Syntax Highlighter performance.

---

crates/story/examples/code-editor.rs
crates/story/examples/large-text.rs
crates/ui/src/input/cursor.rs
crates/ui/src/input/element.rs
crates/ui/src/input/state.rs
crates/ui/src/text/inline.rs
crates/ui/src/text/node.rs

- Removed `Cursor` struct, now use `usize` for selection offset.

input: Refactor start_of_line, end_of_line by use Rope.

---

crates/story/examples/code-editor.rs
crates/ui/src/input/element.rs

editor: Improve CodeEditor inset and line number width.

---

crates/ui/src/input/state.rs
crates/ui/src/input/text_wrapper.rs

Continue #1220 
Now, we can support editing on 100K lines (release mode).
https://github.com/user-attachments/assets/2daccc85-c713-4ddf-b08d-840cb1bb2643

editor: Improve TextWrapper performance by only rebuild changed lines.

---

Cargo.lock
Cargo.toml
crates/story/examples/editor.rs
crates/ui/Cargo.toml
crates/ui/src/highlighter/diagnostics.rs
crates/ui/src/highlighter/highlighter.rs
crates/ui/src/input/cursor.rs
crates/ui/src/input/element.rs
crates/ui/src/input/lsp/completions.rs
crates/ui/src/input/lsp/definitions.rs
crates/ui/src/input/lsp/hover.rs
crates/ui/src/input/mod.rs
crates/ui/src/input/mode.rs
crates/ui/src/input/rope_ext.rs
crates/ui/src/input/search.rs
crates/ui/src/input/state.rs
crates/ui/src/input/text_wrapper.rs
crates/ui/src/inspector.rs
crates/ui/src/text/node.rs

For the License reason.
- The performance is slow down, before version can handle 200K lines, now 150K lines is good.

editor: Revert to use ropey.

---

crates/ui/src/input/popovers/mod.rs
crates/ui/src/text/mod.rs
crates/ui/src/text/node.rs
crates/ui/src/text/style.rs
crates/ui/src/text/text_view.rs

And remove bg, padding for editor hover code blocks.

text_view: Add to support custom code block style.

---

crates/ui/src/input/state.rs
crates/ui/src/input/text_wrapper.rs

1. Avoid use chars.last().
2. Avoid use Rope::eq.

editor: Improve TextWrapper performance.

---

crates/ui/src/input/element.rs
crates/ui/src/input/state.rs
crates/ui/src/input/text_wrapper.rs

This change aim to fix the before version `shape_text` (in Element paint) and `wrap_line` (in TextWrapper cached soft wrap map) may have difference wrap width.
Now move to based on TextWrapper's wrap map to paint text by use `shape_line` method.

input: Use shape line for soft wrap lines.
