Cargo.lock
README.md
assets/icons/ellipsis-vertical.svg
assets/icons/ellipsis.svg
assets/icons/info.svg
assets/icons/plus.svg
crates/ui-story/Cargo.toml
crates/ui-story/src/lib.rs
crates/ui-story/src/list_story.rs
crates/ui-story/src/switch_story.rs
crates/ui/src/icon.rs
crates/ui/src/label.rs
crates/ui/src/list/list_item.rs
crates/ui/src/list/mod.rs
crates/ui/src/picker.rs
crates/ui/src/theme.rs

https://github.com/huacnlee/gpui-component/assets/5518/2554bb6c-94f6-4808-87d6-9a04d7421b26

Add a List example

---

README.md
crates/ui-story/src/list_story.rs
crates/ui-story/src/picker_story.rs
crates/ui/src/button.rs
crates/ui/src/dropdown.rs
crates/ui/src/lib.rs
crates/ui/src/picker.rs
crates/ui/src/scrollbar.rs
crates/ui/src/theme.rs

https://github.com/huacnlee/gpui-component/assets/5518/5e4b7809-f2d0-4e45-a0f2-b9578323a11e

Add Scrollbar

---

README.md
crates/ui-story/src/button_story.rs
crates/ui-story/src/input_story.rs
crates/ui-story/src/lib.rs
crates/ui/src/icon.rs
crates/ui/src/input.rs

Add prefix and suffix to Input.

---

crates/app/src/story_workspace.rs
crates/story/src/button_story.rs
crates/story/src/input_story.rs
crates/story/src/lib.rs
crates/story/src/list_story.rs
crates/story/src/picker_story.rs
crates/story/src/popover_story.rs
crates/story/src/tooltip_story.rs
crates/ui/src/button.rs
crates/ui/src/dropdown.rs
crates/ui/src/focusable.rs
crates/ui/src/input.rs
crates/ui/src/lib.rs
crates/ui/src/styled_ext.rs
crates/ui/src/theme.rs

- Add `FocusableCycle` trait to help impl cycle focus.
- Add `outline` style to StyledExt.

Improve focus

---

crates/app/src/main.rs
crates/story/src/input_story.rs
crates/story/src/lib.rs
crates/story/src/list_story.rs
crates/story/src/picker_story.rs
crates/story/src/popover_story.rs
crates/ui/src/icon.rs
crates/ui/src/lib.rs
crates/ui/src/list/list_item.rs
crates/ui/src/picker.rs
crates/ui/src/popover.rs
crates/ui/src/popup_menu.rs

Add PopupMenu

---

Cargo.lock
crates/ui/Cargo.toml
crates/ui/src/colors.rs
crates/ui/src/default-colors.json
crates/ui/src/lib.rs
crates/ui/src/styled_ext.rs

https://ui.shadcn.com/colors#colors

Add a batch of color methods.

---

Cargo.lock
README.md
assets/icons/loader-circle.svg
assets/icons/loader.svg
crates/app/src/story_workspace.rs
crates/story/src/button_story.rs
crates/story/src/popover_story.rs
crates/story/src/progress_story.rs
crates/story/src/switch_story.rs
crates/ui/Cargo.toml
crates/ui/src/button.rs
crates/ui/src/icon.rs
crates/ui/src/indicator.rs
crates/ui/src/lib.rs
crates/ui/src/progress.rs
crates/ui/src/styled_ext.rs
crates/ui/src/switch.rs
crates/ui/src/theme.rs

https://github.com/user-attachments/assets/cd6410ca-e1c7-459e-8455-d76506b6d305

Add Indicator

---

crates/ui/src/input.rs
crates/ui/src/theme.rs
crates/workspace/src/workspace.rs

Done reset mouse support of https://github.com/zed-industries/zed/pull/13534
https://github.com/user-attachments/assets/71b1d4e4-eef7-4746-8400-b2e3812e5ad4

Add mouse selection support to Input

---

crates/ui/src/input.rs
crates/ui/src/input/blink_cursor.rs
crates/ui/src/theme.rs

Continue #27 
- Fix selection color in dark mode.
- Allow to continue selection, even mouse is out of the input.
- Pause cursor blinking when keep typing.
https://github.com/user-attachments/assets/ce9e722c-5c47-4daa-b2ba-cbe1680c4932

Improve Input

---

README.md
crates/story/src/input_story.rs
crates/ui/src/input.rs

https://github.com/huacnlee/gpui-component/issues/27

Fix placeholder style for Input

---

README.md
crates/ui/src/input.rs

Add double click to select word support for Input.

---

README.md
crates/story/src/progress_story.rs
crates/ui/src/lib.rs
crates/ui/src/slider.rs
crates/ui/src/theme.rs

https://github.com/user-attachments/assets/a1799cd9-45af-413c-b32b-c60fb1b8d586

Add Slider

---

assets/icons/eye-off.svg
assets/icons/eye.svg
crates/story/src/button_story.rs
crates/story/src/checkbox_story.rs
crates/ui/src/button.rs
crates/ui/src/icon.rs
crates/ui/src/label.rs
crates/ui/src/popover.rs

https://github.com/user-attachments/assets/9583ce15-b801-45f9-aafb-54f0ecdf7dc9

Add to masked Label and support children to Button

---

crates/app/src/main.rs
crates/ui/src/input/history.rs
crates/ui/src/input/input.rs
crates/ui/src/input/mod.rs

https://github.com/user-attachments/assets/b898dc08-8e99-4247-8dc3-d5752d1bc2f3
Ref https://github.com/huacnlee/gpui-component/issues/27

Add to support Input history for undo & redo

---

crates/story/src/table_story.rs
crates/ui/src/table.rs
crates/ui/src/theme.rs

https://github.com/user-attachments/assets/d56f2cd7-df08-437b-9eea-849d68094e1f

Add to support Table column resizing.

---

README.md
crates/story/src/table_story.rs
crates/ui/src/table.rs

https://github.com/user-attachments/assets/9964f3da-0376-4b53-b64e-c9652c324aa3

table: Add drag to move col.

---

crates/ui/src/resizable/panel.rs
crates/ui/src/table.rs

https://github.com/user-attachments/assets/a8d2abcb-9122-4060-bfd6-2673903c18a1

resizable: Fix resizable handle to keep showing drag style on dragging.

---

Cargo.toml
crates/story/src/checkbox_story.rs
crates/ui/src/checkbox.rs
crates/ui/src/label.rs
crates/ui/src/radio.rs

Fix Label, Checkbox, Radio to support label text wrap.

---

crates/story/src/popover_story.rs
crates/ui/src/icon.rs
crates/ui/src/popup_menu.rs

Update PopupMenu to support checked style.

---

assets/icons/menu.svg
crates/story/src/button_story.rs
crates/story/src/popover_story.rs
crates/ui/src/button.rs
crates/ui/src/checkbox.rs
crates/ui/src/icon.rs
crates/ui/src/indicator.rs
crates/ui/src/selectable.rs
crates/ui/src/theme.rs

- Update `primary`, `danger`, `outline`, `ghost`, `link` methods to as a builder method to just change style.
- Add `compact` used to reduce padding.

Add Link style Button

---

crates/story/src/dropdown_story.rs
crates/ui/src/dropdown.rs
crates/ui/src/list/list_item.rs

- Add SearchableVec to let Dropdown support search filter.
- Fix dropdown title overflow.
- Add to support custom dropdown right icon.
https://github.com/user-attachments/assets/b9e28fce-3e0f-44f7-a0f4-3e01f6db31d1

Improve Dropdown to Add search support and custom icon

---

crates/ui/src/input/input.rs
crates/ui/src/popup_menu.rs

Improve PopupMenu style

---

Cargo.lock
crates/story/src/picker_story.rs
crates/ui/src/list/list.rs
crates/ui/src/list/list_item.rs
crates/ui/src/svg_img.rs

- Add confirmed to ListItem to show check style.

Fix list next to select first item, cancel to deselect item.

---

crates/ui/src/scroll/scrollbar.rs
crates/ui/src/theme.rs

https://github.com/user-attachments/assets/c7c3b9c1-d458-438d-bf78-3b5bc2ddcd5c

Add to support click Scrollbar to scroll and fix thumb position when dragging.

---

crates/story/src/calendar_story.rs
crates/ui/src/time/calendar.rs
crates/ui/src/time/date_picker.rs

https://github.com/user-attachments/assets/b6232d8e-0832-449d-a982-49e015232cfa

datepicker: Add Year, Month select mode.

---

README.md
crates/story/src/calendar_story.rs
crates/ui/src/time/calendar.rs
crates/ui/src/time/date_picker.rs
crates/ui/src/time/utils.rs

https://github.com/user-attachments/assets/cc934401-78c5-42d6-afc8-a365fea2129b

Add DateRangePicker

---

crates/ui/src/time/calendar.rs
crates/ui/src/time/utils.rs

Fix to display correct days in calendar view.

---

crates/ui/src/table.rs

https://github.com/user-attachments/assets/0836014d-9240-4e77-9daf-dd1ef8d81cd5

Improve Table head to not show selected bg and remove drag border color.

---

crates/ui/src/time/date_picker.rs

datepicker: Fix calender popup background.

---

crates/ui/src/dropdown.rs
crates/ui/src/time/date_picker.rs

Fix Dropdown and DatePicker anchor to snap to window.

---

Cargo.lock
README.md
assets/icons/circle-check.svg
assets/icons/triangle-alert.svg
crates/app/src/story_workspace.rs
crates/story/src/modal_story.rs
crates/ui/Cargo.toml
crates/ui/src/icon.rs
crates/ui/src/lib.rs
crates/ui/src/notification.rs
crates/ui/src/root.rs

https://github.com/user-attachments/assets/8a10bff7-f669-471e-8516-2a64ae95ae0a

Add Notification

---

crates/story/src/dropdown_story.rs
crates/story/src/input_story.rs
crates/story/src/lib.rs
crates/ui/locales/ui.yml
crates/ui/src/dropdown.rs

Close Dropdown menu on blur.

---

crates/ui/src/history.rs
crates/ui/src/input/change.rs
crates/ui/src/input/input.rs
crates/ui/src/input/mod.rs
crates/ui/src/lib.rs

Ref https://github.com/huacnlee/gpui-component/issues/161
For example: Used to do Back/Forward

Extract `History` to a common design to support more cases.

---

crates/story/src/lib.rs
crates/story/src/popup_story.rs
crates/ui/src/popup_menu.rs
crates/ui/src/theme.rs

Add KeyBinding to MenuItem.

---

crates/ui/src/button.rs

* Set the background opacity when loading
* Do not trigger the on click event when loading

Improve the loading button

---

crates/story/src/resizable_story.rs
crates/ui/src/dock/stack_panel.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/resizable/mod.rs
crates/ui/src/resizable/panel.rs

https://github.com/user-attachments/assets/b2c50949-7310-4d3d-8276-5bf15cf3ba9f

Better Panel resize.

---

crates/story/src/popup_story.rs
crates/ui/src/modal.rs
crates/ui/src/popover.rs
crates/ui/src/popup_menu.rs

Popover content supports setting the maximum width

---

crates/story/src/table_story.rs
crates/ui/src/table.rs

https://github.com/user-attachments/assets/03001a21-6a3d-4c06-a00c-9dea8208e357

table: Add `load_more` delegate method and called when scrolled near the bottom.

---

crates/ui/src/animation.rs
crates/ui/src/lib.rs
crates/ui/src/modal.rs
crates/ui/src/notification.rs
crates/ui/src/styled.rs

Ref #148 
https://github.com/user-attachments/assets/c09adc18-554c-4300-8109-98f3ab183910

Add `cubic_bezier` method and change modal to use this.

---

crates/app/src/story_workspace.rs
crates/story/src/input_story.rs
crates/ui/src/color_picker.rs
crates/ui/src/colors.rs
crates/ui/src/dropdown.rs
crates/ui/src/styled.rs
crates/ui/src/theme.rs

https://github.com/user-attachments/assets/be5fc290-0464-4356-9f97-c35720e3e11d

Improve ColorPicker to support input hex color.

---

crates/ui/src/resizable/panel.rs

https://github.com/user-attachments/assets/8605b82e-6113-41d1-a9c4-0ba7d55968ba

dock: Fix panel that can not auto resize when it have initial size.

---

crates/app/src/story_workspace.rs
crates/ui/src/dock/stack_panel.rs
crates/ui/src/resizable/panel.rs

https://github.com/user-attachments/assets/7177bd8f-5b19-4959-8d60-cae583173e73

dock: Fix add_panel with placement to split size.

---

crates/story/src/button_story.rs
crates/ui/src/button.rs
crates/ui/src/button_group.rs
crates/ui/src/lib.rs

Add ButtonGroup

---

Cargo.lock
crates/ui/src/color_picker.rs
crates/ui/src/context_menu.rs
crates/ui/src/dropdown.rs
crates/ui/src/popover.rs
crates/ui/src/time/date_picker.rs

- Also update GPUI.
Ref: https://github.com/zed-industries/zed/pull/17159

Improve popup snap to window with margin.

---

crates/app/src/story_workspace.rs
crates/story/src/modal_story.rs
crates/ui/src/dropdown.rs
crates/ui/src/lib.rs
crates/ui/src/modal.rs
crates/ui/src/root.rs

modal: Add to support open multiple Modals.

---

crates/ui/src/checkbox.rs
crates/ui/src/modal.rs
crates/ui/src/popup_menu.rs
crates/ui/src/radio.rs

ui: Improve UI details (Modal, Checkbox, Radio and MenuItem)

---

crates/ui/src/button.rs

button: Hotfix Button to valign text center.

---

crates/ui/src/scroll/scrollbar.rs

scrollbar: Fix Scrollbar inset and remove bar border.

---

crates/story/src/button_story.rs
crates/story/src/calendar_story.rs
crates/story/src/dropdown_story.rs
crates/story/src/icon_story.rs
crates/story/src/image_story.rs
crates/story/src/input_story.rs
crates/story/src/lib.rs
crates/story/src/list_story.rs
crates/story/src/modal_story.rs
crates/story/src/popup_story.rs
crates/story/src/progress_story.rs
crates/story/src/resizable_story.rs
crates/story/src/scrollable_story.rs
crates/story/src/switch_story.rs
crates/story/src/table_story.rs
crates/story/src/text_story.rs
crates/story/src/tooltip_story.rs
crates/story/src/webview_story.rs
crates/ui/src/dock/panel.rs
crates/ui/src/dock/stack_panel.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/modal.rs
crates/ui/src/root.rs

- modal: Improve modal focus take, when modal close, make sure focus back.
- modal: Fix hover close button will cross to back modal on multiple modal layer.
- panel: Add focus handle to Panel and TabPanel.
- panel: Update title method to return `AnyElement`.

modal: Improve Modal and Panel focus handle.

---

crates/ui/src/button.rs
crates/ui/src/checkbox.rs
crates/ui/src/radio.rs

windows: Fix button and checkbox line-height again.

---

crates/ui/src/input/input.rs

Revert old implementation
- https://github.com/huacnlee/gpui-component/pull/26
- https://github.com/zed-industries/zed/pull/14340
https://github.com/user-attachments/assets/52ce2e3a-3e1d-4ba2-af42-76b1df987404
https://github.com/user-attachments/assets/9aa8cfe1-5928-4d20-b534-806140c7ee59
https://github.com/user-attachments/assets/c913248e-b1dc-46d6-a517-e1231e606171

input: Update Input selection behavior to like OS input.

---

crates/story/src/modal_story.rs
crates/ui/src/color_picker.rs
crates/ui/src/dropdown.rs
crates/ui/src/modal.rs
crates/ui/src/root.rs
crates/ui/src/styled.rs
crates/ui/src/time/date_picker.rs

- Fix dropdown to mouse down out to dismiss.
https://github.com/user-attachments/assets/f5ab4aca-bfdc-460e-ae5a-cd0a31a30906

modal: Only focus modal when it not focused on.

---

crates/story/src/popup_story.rs
crates/ui/src/popover.rs

And add popover self dismiss example.
```rs
cx.emit(DismissEvent);
```

popover: Fix PopoverContent content build to use ViewContext<Self>.

---

crates/story/src/table_story.rs
crates/ui/src/table.rs

Toggle stripe and number of rows in Table Story

---

Cargo.lock
crates/story/Cargo.toml
crates/story/src/table_story.rs

The example that used: 6000 rows x 60 cols, and refresh data every 100ms.
The CPU usage: 40% (macOS M4)
https://github.com/user-attachments/assets/40d6c64f-c658-4c7a-9251-fb76e17ec543

story: Add very complex table data update example to test performance.

---

crates/story/src/table_story.rs
crates/ui/src/table.rs

table: Add `size` to Table to support Large, Medium(default), Small, XSmall.

---

crates/app/src/story_workspace.rs
crates/ui/src/button.rs

The point is add `.font_family(".SystemUIFont")` to root view.

button: Fix Button text to align vertical center.

---

crates/ui/src/input/input.rs

Ref: https://support.apple.com/en-hk/102650

input: Move caret to line start or end with selected content

---

crates/story/src/table_story.rs
crates/ui/src/table.rs

- Update first sort behaviour to `descending`.

table: Fix table sort icon display.

---

.gitignore
.vscode/settings.json
crates/app/src/story_workspace.rs
crates/ui/src/dock/dock.rs
crates/ui/src/dock/mod.rs
crates/ui/src/dock/panel.rs
crates/ui/src/dock/stack_panel.rs
crates/ui/src/dock/state.rs
crates/ui/tests/fixtures/layout.json

The dock state have been updated to use `DockAreaState`.

dock: Add to support save left, right, bottom dock state.

---

crates/ui/src/tooltip.rs

tooltip: Fix Tooltip text line-height.

---

crates/story/src/modal_story.rs

story: Fix modal story button style.

---

crates/ui/src/table.rs

table: Fix to render table vertical scrollbar under the head.

---

crates/ui/src/dock/stack_panel.rs
crates/ui/src/dock/tab_panel.rs

Continue #297 #309
```
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
[1]    45068 abort      cargo run
```

dock: Fix toggle button check will stack overflow bug.

---

Cargo.lock
Cargo.toml
crates/app/src/story_workspace.rs
crates/story/src/input_story.rs
crates/story/src/webview_story.rs
crates/ui/Cargo.toml
crates/ui/src/webview.rs

- Closes #316 
- Ref https://github.com/tauri-apps/wry/pull/1385
https://github.com/user-attachments/assets/cc614334-47fe-4722-8745-aea783fbab4a
On macOS, now the IME bug is gone.
https://github.com/user-attachments/assets/363bb016-229f-4766-84f7-6a4838e490bf
https://github.com/user-attachments/assets/320c5c1c-cfac-4165-af8a-bc9708952460

webview: Blur WebView when clicked out to fix IME cannot input bug.

---

crates/story/src/table_story.rs
crates/ui/src/styled.rs
crates/ui/src/table.rs

Add `col_padding` to Table delegate to control the column padding.

---

crates/ui/src/dock/dock.rs
crates/ui/src/dock/mod.rs
crates/ui/src/dock/stack_panel.rs
crates/ui/src/dock/state.rs
crates/ui/src/dock/tab_panel.rs

- Fix emit `PanelEvent::LayoutChanged` when panel resized.

dock: Fix zoom support for side dock panel.

---

crates/ui/src/popup_menu.rs
crates/ui/src/scroll/scrollbar.rs

menu: Fix Menu scrollbar will always showing bug.

---

crates/ui/src/resizable/panel.rs

The essence of the problem is that flex_basis initial_size and flex_basis size are in conflict: the size overwrites the initial_size percentage and loses the original percentage in extremely narrow parent groups, so we have to add the field to the state persisting the desired percentage.
Fix #262

resizable: Keep the ratio when adjust widths (rather than falling back to 33.33% when resizing back)

---

crates/story/src/popup_story.rs
crates/ui/src/popup_menu.rs

menu: Add `menu_with_element` to add a custom render item.

---

Cargo.lock

Ref:
- https://github.com/zed-industries/zed/pull/19189
- https://github.com/zed-industries/zed/pull/18729#issuecomment-2410445980

Update GPUI to revert `taffy` for performance.

---

Cargo.lock
crates/app/src/story_workspace.rs
crates/story/src/webview_story.rs
crates/ui/Cargo.toml
crates/ui/src/webview.rs

To match Wry recently API changes.
Ref: https://github.com/tauri-apps/wry/pull/1385

webview: Update wry.

---

crates/app/src/story_workspace.rs
crates/story/src/dropdown_story.rs

- Remove WebView story.
- Fix dropdown size.

story: Fix story caes

---

crates/story/src/table_story.rs
crates/ui/src/table.rs

table: Improve `render_tr` to bind the `context_menu`

---

crates/ui/src/drawer.rs
crates/ui/src/lib.rs
crates/ui/src/root.rs

drawer: support ESC to close it by on_action and call on_close

---

crates/ui/src/button.rs
crates/ui/src/button_group.rs
crates/ui/src/checkbox.rs
crates/ui/src/context_menu.rs
crates/ui/src/divider.rs
crates/ui/src/dropdown.rs
crates/ui/src/event.rs
crates/ui/src/history.rs
crates/ui/src/input/clear_button.rs
crates/ui/src/input/input.rs
crates/ui/src/input/otp_input.rs
crates/ui/src/label.rs
crates/ui/src/lib.rs
crates/ui/src/link.rs
crates/ui/src/list/list.rs
crates/ui/src/list/list_item.rs
crates/ui/src/notification.rs
crates/ui/src/popup_menu.rs
crates/ui/src/progress.rs
crates/ui/src/radio.rs
crates/ui/src/root.rs
crates/ui/src/skeleton.rs
crates/ui/src/slider.rs
crates/ui/src/switch.rs
crates/ui/src/time/date_picker.rs

- Better icon style in Input, Dropdown, DatePicker.

chore: Update controls detail.

---

crates/app/src/story_workspace.rs
crates/story/src/dropdown_story.rs
crates/ui/src/theme.rs

- Fix #334 to keep selected theme color.

theme: Add `apply_color` to theme to support merge a new color into theme color.

---

README.md
crates/app/src/story_workspace.rs
crates/story/src/accordion_story.rs
crates/story/src/lib.rs
crates/ui/src/accordion.rs
crates/ui/src/lib.rs
crates/ui/src/theme.rs

accordion: Add Accordion.

---

Cargo.lock
crates/story/src/modal_story.rs
crates/ui/src/drawer.rs
crates/ui/src/theme.rs
crates/ui/src/title_bar.rs

theme: Update GPUI and imporve dark color.

---

crates/story/src/list_story.rs
crates/story/src/modal_story.rs
crates/ui/src/dropdown.rs
crates/ui/src/list/list.rs

Following #360 TableDelegate changes.

list: Add `cx` argument to ListDelegate.

---

crates/story/src/table_story.rs
crates/ui/src/context_menu.rs
crates/ui/src/list/list.rs
crates/ui/src/popup_menu.rs
crates/ui/src/table.rs
crates/ui/src/theme.rs

- table: Add `content_menu` to TableDelegate.

table, list: Add right clicked row style and improve selection style.

---

crates/ui/src/list/list.rs
crates/ui/src/table.rs

table, list: Avoid use deferred to show selected row style.

---

crates/story/src/calendar_story.rs
crates/ui/src/time/calendar.rs
crates/ui/src/time/date_picker.rs

Preset Ranges have been added. The “Today” border has also been added.

Add the Preset Ranges and add border for today

---

Cargo.lock
crates/app/src/story_workspace.rs

linux: Fix #104 Linux platform crash with BorrowMutError.

---

crates/ui/src/input/input.rs

Fix #331
It is ensured that the scroll offset remains consistent during parent container resizing, preventing the cursor from being forced back into view unless the user interacts with the input, providing a more consistent user experience in scenarios where automatic scrolling during resizing is undesirable.
This behavior aligns with common text editors and input fields where resizing the window doesn't force the cursor back into view.

input: Ensure resizing the window doesn't force the cursor back into view

---

crates/ui/src/button.rs

If you want the button to be flexible, add `flex_shrink`.

button: Add `flex_shrink_0` to the base

---

Cargo.lock
crates/ui/Cargo.toml

https://github.com/tauri-apps/wry/releases/tag/wry-v0.46.3

webview: Upgrade wry version to fixed with_user_agent regression.

---

crates/ui/src/scroll/scrollbar.rs

scrollbar: show the narrower scrollbar in idle state

---

crates/story/src/calendar_story.rs
crates/ui/src/time/calendar.rs
crates/ui/src/time/date_picker.rs

calendar: Add small, medium, large size support to Calendar.

---

crates/ui/src/button.rs
crates/ui/src/theme.rs

- Fix `lighten`, `darken` method for Hsla.

button: Fix Button disabled style.

---

Cargo.lock
Cargo.toml
crates/story/src/fixtures/pie.json
crates/story/src/image_story.rs
crates/story/src/lib.rs
crates/ui/Cargo.toml
crates/ui/src/svg_img.rs

svg_img: Render SVGs with text tags

---

crates/story/src/image_story.rs
crates/ui/src/svg_img.rs

svg_img: Remove the `svg_img` method

---

crates/story/src/lib.rs
crates/ui/src/dock/panel.rs
crates/ui/src/dock/tab_panel.rs

panel: Add `toolbar_buttons` to extend button to panel.

---

crates/story/src/modal_story.rs
crates/ui/src/webview.rs

webview: Add `bounds` method to WebView to get container bounds.

---

crates/app/src/story_workspace.rs
crates/ui/src/dock/dock.rs
crates/ui/src/dock/mod.rs
crates/ui/src/dock/state.rs
crates/ui/src/dock/tab_panel.rs

dock: Generalize Dock's panel to accommodate DockItem

---

crates/app/src/story_workspace.rs
crates/ui/src/dock/dock.rs
crates/ui/src/dock/mod.rs
crates/ui/src/dock/stack_panel.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/dock/toggle_buttons.rs

Draft https://github.com/longbridgeapp/gpui-component/pull/414 to keep old code.

dock: Remove the inside toggle dock button in Dock to reduce complex and add dock::ToggleButtons.

---

crates/ui/src/dock/mod.rs

Reverts longbridgeapp/gpui-component#419

Revert "dock: Change bottom dock to floating on bottom of the center view."

---

crates/ui/src/dock/invalid_panel.rs
crates/ui/src/dock/state.rs

dock: Keep the panel state when meet invalid panel.

---

Cargo.lock
crates/ui/src/dock/dock.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/list/list.rs
crates/ui/src/resizable/panel.rs
crates/ui/src/scroll/scrollable_mask.rs
crates/ui/src/scroll/scrollbar.rs
crates/ui/src/slider.rs
crates/ui/src/table.rs

Refs:
- https://github.com/zed-industries/zed/pull/20349
- https://github.com/zed-industries/zed/pull/20371
- https://github.com/zed-industries/zed/pull/20686

chore: Upgrade GPUI and fix API changes.

---

crates/ui/src/table.rs

Before: ~85 - 100FPS
After:  ~110 - 115FPS

table: Improve table render performance.

---

crates/story/src/input_story.rs
crates/ui/src/input/input.rs
crates/ui/src/lib.rs
crates/ui/src/number_input.rs

https://github.com/user-attachments/assets/ae6f4e48-b0fa-4f8c-bff5-809c70848b06

ui: Add `number_input`

---

Cargo.lock
crates/ui/src/input/input.rs

Ref https://github.com/zed-industries/zed/pull/20968

input: Update GPUI and fix Input changes.

---

Cargo.lock
assets/icons/layout-dashboard.svg
crates/app/Cargo.toml
crates/app/src/story_workspace.rs
crates/story/src/popup_story.rs
crates/story/src/text_story.rs
crates/ui/src/dock/dock.rs
crates/ui/src/dock/mod.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/icon.rs

Ref #438 
https://github.com/user-attachments/assets/93b40aed-39f3-4d16-a442-13aa7a931895

dock: Add `add_panel` method to add panel to DockArea.

---

crates/story/src/table_story.rs
crates/ui/src/colors.rs

```rs
ui::red(50);
ui::blue(600);
```

theme: Add color method for default color palette to get color by a scale number.

---

crates/ui/src/scroll/scrollbar.rs

And increase scrollbar thumb color in normal mode.
But, it looks like no difference for performance.

scrollbar: Use `paint_layer` for scrollbar paint.

---

crates/story/src/progress_story.rs
crates/ui/src/divider.rs

divider: Support custom colors

---

crates/app/src/story_workspace.rs
crates/story/src/button_story.rs
crates/story/src/icon_story.rs
crates/story/src/input_story.rs
crates/story/src/modal_story.rs
crates/story/src/popup_story.rs
crates/story/src/table_story.rs
crates/story/src/text_story.rs
crates/story/src/tooltip_story.rs
crates/ui/src/button.rs
crates/ui/src/button_group.rs
crates/ui/src/clipboard.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/drawer.rs
crates/ui/src/input/clear_button.rs
crates/ui/src/modal.rs
crates/ui/src/notification.rs
crates/ui/src/number_input.rs
crates/ui/src/sidebar/mod.rs
crates/ui/src/time/calendar.rs
crates/ui/src/time/date_picker.rs

This is a breaking changes, we need refactor exist code by this:
- `ButtonStyled` -> `ButtonVariants`
- `.style` -> `.with_variant`
- `ButtonStyle` -> `ButtonVariant`
- `ButtonCustomStyle` -> `ButtonCustomVariant`

button: Rename `ButtonStyle` to `ButtonVariant`.

---

README.md
crates/story/src/sidebar_story.rs
crates/ui/src/breadcrumb.rs
crates/ui/src/lib.rs
crates/ui/src/link.rs

breadcrumb: Add Breadcrumb.

---

README.md
crates/story/src/lib.rs
crates/story/src/text_story.rs
crates/ui/src/badge.rs
crates/ui/src/lib.rs

badge: Add Badge.

---

crates/story/src/lib.rs

story: Revert `scrollable` for StoryContainer for fix size_full.

---

Cargo.lock
crates/ui/src/scroll/scrollbar.rs
crates/ui/src/theme.rs

scrollbar: Adjust scrollbar style and add `scrollbar_thumb_hover` to theme.

---

crates/ui/src/button.rs
crates/ui/src/theme.rs

theme: Fix `lighten`, `darken` method.

---

crates/ui/src/button.rs
crates/ui/src/theme.rs

theme: Fix secondary active color in light mode.

---

crates/story/src/lib.rs
crates/ui/src/dock/panel.rs
crates/ui/src/dock/tab_panel.rs

It will called when the panel active, zoom state changed.

panel: Add `set_active`, `set_zoomed` method to Panel trait.

---

crates/ui/src/input/input.rs

input: Up, Down to keep the same column if it possible

---

crates/ui/src/resizable/panel.rs

This change for make sure when Panel to hide and show, the original panel size will keep.

panel: To keep panel size when it going to hidden.

---

crates/ui/src/resizable/panel.rs

https://github.com/user-attachments/assets/9174033b-d901-412f-9176-cdef6438822f

panel: Fix panel to unexpected size chagnes when moved some panel.

---

crates/ui/src/scroll/scrollable_mask.rs

table: Fix to only handle one way scrolling at same time.

---

crates/story/src/modal_story.rs
crates/ui/src/drawer.rs
crates/ui/src/root.rs

This change to make sure notification will display when WebView render on the drawer.

drawer: Render notification at the side of drawer when drawer (top, right) it opened.

---

crates/story/examples/tiles.rs
crates/story/src/main.rs
crates/ui/src/lib.rs
crates/ui/src/root.rs
crates/ui/src/title_bar.rs
crates/ui/src/window_border.rs

And fix the title bar buttons click handle on Linux.

root: Add window shadow to Root for support window border style on Linux.

---

crates/ui/src/drawer.rs
crates/ui/src/modal.rs
crates/ui/src/root.rs
crates/ui/src/window_border.rs

- Update `overlay` for Modal, still handle click out to dismiss, even it no overlay.

modal: Fix modal, drawer overlay position on Linux.

---

crates/ui/src/list/list.rs
crates/ui/src/list/list_item.rs
crates/ui/src/popup_menu.rs

Closes #519 to fix popup_menu attempt to subtract with overflow bug.

list: Fix selected and confirmed list item detail.

---

crates/story/src/main.rs

title_bar: Avoid zoom window on double clicked on title bar right area.

---

crates/ui/src/input/element.rs
crates/ui/src/input/input.rs

Close #494
- Fix enter to newline.
- Fix to ensure scroll on move cursor or enter.

input: Fix TextArea enter to newline not work and scroll to visible on move cursor.

---

crates/ui/src/input/input.rs

input: Handle moving above the first line

---

crates/ui/src/input/input.rs

input: Fix TextInput cursor getting stuck on Down key press

---

crates/story/src/table_story.rs
crates/ui/src/table.rs

- Add `TableEvent::DoubleClickedRow` to emit double clicked row event to table.

table: Binding popup menu on the table not on row for avoid render it on each rows.

---

crates/ui/src/input/input.rs

input: Support Cmd+Up, Cmd+Down, Cmd+Shift+Up, Cmd+Shift+Down

---

crates/ui/src/popup_menu.rs

popup_menu: More compact checked style

---

crates/story/src/icon_story.rs
crates/story/src/image_story.rs
crates/story/src/lib.rs
crates/story/src/sidebar_story.rs
crates/story/src/tooltip_story.rs
crates/ui/src/dock/panel.rs
crates/ui/src/dock/tab_panel.rs

dock: Add `ToolbarType` for pinning the toolbar button

---

crates/story/src/list_story.rs
crates/story/src/table_story.rs
crates/ui/src/list/list.rs
crates/ui/src/list/loading.rs
crates/ui/src/list/mod.rs
crates/ui/src/skeleton.rs
crates/ui/src/table.rs
crates/ui/src/table/loading.rs

list, table: Add default loading animation to List and Table.

---

crates/ui/src/list/list.rs
crates/ui/src/table.rs

- Default `threshold` changed to 20.

chore: Improve Table, List load more threshold, and avoid duplicate request.

---

crates/story/src/progress_story.rs
crates/ui/src/colors.rs
crates/ui/src/slider.rs
crates/ui/src/theme.rs

- Fix to support stop at any position.
- Fix click bounds.

slider: Add vertical and reverse support to Slider.

---

crates/ui/src/input/input.rs

The `selected_range` should be UTF-8.

input: Fix crash cause by incorrect selected range. 

---

crates/story/examples/input.rs
crates/story/examples/list.rs
crates/story/examples/sidebar.rs
crates/story/examples/table.rs
crates/story/src/lib.rs

```bash
cargo run --example table
cargo run --example list
```

example: Split single examples.

---

Cargo.lock
crates/ui/src/input/input.rs

Close #581
Ref https://github.com/zed-industries/zed/pull/23668
https://github.com/user-attachments/assets/c69d098e-d2cb-4053-b739-6c7dd666e769

input: Fix position cursor in multi-line mode.

---

Cargo.lock
crates/story/src/modal_story.rs
crates/story/src/scrollable_story.rs
crates/story/src/sidebar_story.rs
crates/story/src/text_story.rs
crates/ui/src/color_picker.rs
crates/ui/src/dock/dock.rs
crates/ui/src/dock/mod.rs
crates/ui/src/dock/stack_panel.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/dock/tiles.rs
crates/ui/src/dropdown.rs
crates/ui/src/input/input.rs
crates/ui/src/list/list.rs
crates/ui/src/popup_menu.rs
crates/ui/src/resizable/panel.rs
crates/ui/src/root.rs
crates/ui/src/slider.rs
crates/ui/src/table.rs
crates/ui/src/webview.rs

Ref 
- https://github.com/zed-industries/zed/pull/23693
- https://github.com/zed-industries/zed/pull/23688

chore: Upgrade for GPUI API changes.

---

crates/ui/Cargo.toml
crates/ui/src/input/input.rs

Close #466 
https://github.com/user-attachments/assets/48cda905-f2bf-4896-b3ae-08b7cd61467d

input: Add to support move, select and delete by word.

---

crates/ui/src/theme.rs

- Removed unused `cx.theme().panel` variable.

theme: Add doc for Theme variables.

---

crates/story/src/tooltip_story.rs
crates/ui/src/tooltip.rs

tooltip: Support render element

---

Cargo.toml
README.md
crates/story/Cargo.toml
crates/story/src/accordion_story.rs
crates/story/src/button_story.rs
crates/story/src/calendar_story.rs
crates/story/src/dropdown_story.rs
crates/story/src/form_story.rs
crates/story/src/icon_story.rs
crates/story/src/image_story.rs
crates/story/src/input_story.rs
crates/story/src/lib.rs
crates/story/src/list_story.rs
crates/story/src/main.rs
crates/story/src/modal_story.rs
crates/story/src/popup_story.rs
crates/story/src/progress_story.rs
crates/story/src/resizable_story.rs
crates/story/src/scrollable_story.rs
crates/story/src/sidebar_story.rs
crates/story/src/switch_story.rs
crates/story/src/table_story.rs
crates/story/src/text_story.rs
crates/story/src/title_bar.rs
crates/story/src/tooltip_story.rs
crates/story/src/webview_story.rs

Update dependencies from `ui` to `gpui-component`.

Rename package from `ui` to `gpui-component`

---

crates/story/src/table_story.rs
crates/ui/src/scroll/scrollbar.rs
crates/ui/src/table.rs

scrollbar: Add max_fps to limit drag scroll update rate for reduce CPU usage.

---

README.md
crates/ui/src/dock/dock.rs
crates/ui/src/dock/tab_panel.rs

* This may cause the interface to not update in real time.

dock: Revert `AnyView` cached

---

crates/story/examples/tiles.rs

example: Fix `tiles` needs package gpui-component

---

Cargo.lock
crates/story/Cargo.toml
crates/story/src/modal_story.rs
crates/story/src/webview_story.rs
crates/ui/src/drawer.rs
crates/ui/src/input/element.rs
crates/ui/src/input/input.rs
crates/ui/src/svg_img.rs

- Replace `Window::parent_view_id()` with `Window::current_view()` https://github.com/zed-industries/zed/pull/24212
- Fix SvgImg crash by move `use_asset` to `request_layout`.
- Fix Input to implement `character_index_for_point` method https://github.com/zed-industries/zed/pull/23989
- Fix Input IME position to under the cursor line.
    <img width="504" alt="image" src="https://github.com/user-attachments/assets/8a6f56c8-6aae-4c0c-8c5a-3959d6a9d224" />
- Fix Input overflow sub crash.

chore: Upgrade GPUI 2025/02/10

---

crates/story/src/list_story.rs
crates/ui/src/dock/dock.rs
crates/ui/src/popup_menu.rs
crates/ui/src/resizable/panel.rs
crates/ui/src/window_border.rs

Ref https://github.com/zed-industries/zed/discussions/24260#discussioncomment-12135749

chore: Avoid some unnecessary `window.refresh` call.

---

crates/ui/src/dropdown.rs
crates/ui/src/list/list.rs

https://github.com/user-attachments/assets/e33c2324-94f0-42b0-99cc-9e2dcdee3f3d
https://github.com/user-attachments/assets/7c5c6fee-b0f6-4cd5-986e-ea8f6f0e7f9d

dropdown: Do not reset the selected index when cancelling

---

README.md

chore: Update README for icons usage.

---

crates/story/examples/scrollable.rs
crates/story/src/scrollable_story.rs
crates/story/src/title_bar.rs
crates/ui/src/button/button_group.rs
crates/ui/src/scroll/scrollbar.rs
crates/ui/src/table.rs
crates/ui/src/theme.rs

Close #573
- Fix theme settings to keeping when switch theme mode.

theme: Add to support always show scrollbar mode and default to match with system style.

---

crates/ui/src/dock/dock.rs
crates/ui/src/resizable/panel.rs
crates/ui/src/resizable/resize_handle.rs

https://github.com/user-attachments/assets/aabbd73b-3c11-43e2-a4f2-121d46fba1d7

panel: Improve resize handle to show highlight color on dragging.

---

crates/story/src/calendar_story.rs
crates/ui/src/time/calendar.rs
crates/ui/src/time/date_picker.rs

| Day Of Week | Interval | Range |
|--------------|---------|-------|
| <img width="420" alt="image" src="https://github.com/user-attachments/assets/e23f69b8-3191-4370-8adf-266362680e5c" /> | <img width="264" alt="image" src="https://github.com/user-attachments/assets/c211d7c3-9878-402e-a6cc-e3ac1b50e588" /> | <img width="337" alt="image" src="https://github.com/user-attachments/assets/2b894ef1-14d0-4fc3-89e5-4e38b5e8572c" /> |

calendar: Add `Matcher` for disabled dates

---

crates/story/src/list_story.rs
crates/ui/src/scroll/scrollbar.rs
crates/ui/src/table.rs

And revert some #621 wrong changes for hover to show scrollbar.

scrollbar: Update scrollbar hitbox to it bounds, not fill the full of parent view.

---

crates/story/examples/modal.rs
crates/story/src/lib.rs

```
cargo run --example modal
```

example: Add `modal` example.

---

crates/story/src/sidebar_story.rs
crates/ui/src/sidebar/menu.rs

Close #471
```
Finished `release` profile [optimized] target(s) in 9.99s
Running `target/release/examples/sidebar`
[1]    30606 segmentation fault  cargo run --example sidebar --release
```
This may cause by used `map` break by maybe Rust compiler bug, I detected that if I remove a `map`, then the crash will gone.
So, this changes to refactor the Sidebar API to avoid use `map`.

sidebar: Refactor Sidebar API to avoid `map` call will segmentation fault on release.

---

Cargo.toml
README.md
crates/story/Cargo.toml
crates/story/examples/webview.rs
crates/ui/Cargo.toml
crates/ui/src/lib.rs

webview: Let `webview` as a feature and not default enable.

---

crates/story/examples/switch.rs
crates/story/src/switch_story.rs
crates/ui/src/checkbox.rs
crates/ui/src/radio.rs
crates/ui/src/switch.rs
crates/ui/src/text/element.rs
crates/ui/src/text/html.rs
crates/ui/src/text/markdown.rs
crates/ui/src/text/mod.rs
crates/ui/src/tooltip.rs

- Add `style` method to TextView.
- Add `inline` method to TextView to use default inline style.

text_view: Update Switch, Checkbox, Radio to let label method support TextView.

---

Cargo.lock
crates/story/examples/description_list.rs
crates/ui/src/description_list.rs
crates/ui/src/lib.rs
crates/ui/src/styled.rs
crates/ui/src/text/html.rs
crates/ui/src/text/markdown.rs
crates/ui/src/theme.rs

description_list: Add `DescriptionList`.

---

crates/story/examples/markdown.md
crates/ui/src/text/element.rs
crates/ui/src/text/markdown.rs

- Show table cell vertical border.

text_view: Fix markdown table alignment.

---

crates/ui/src/dock/dock.rs
crates/ui/src/dock/mod.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/dock/tiles.rs

- Add `remove_panel` method to DockArea.

tiles: To support close panel.

---

Cargo.lock
crates/ui/src/text/element.rs

Close #643
Ref https://github.com/zed-industries/zed/pull/25632

text_view: Fix img height in TextView.

---

crates/story/src/scrollable_story.rs
crates/ui/src/scroll/scrollbar.rs

Fix #624 was broke scroll to show behaviors.

scrollbar: Fix scroll to show scrollbar.

---

Cargo.lock
README.md
crates/story/Cargo.toml
crates/story/examples/markdown.md
crates/story/examples/markdown.rs
crates/ui/Cargo.toml
crates/ui/src/highlighter/highlight.rs
crates/ui/src/highlighter/mod.rs
crates/ui/src/highlighter/themes/README.md
crates/ui/src/highlighter/themes/dark.tmTheme
crates/ui/src/highlighter/themes/light.tmTheme
crates/ui/src/lib.rs
crates/ui/src/text/element.rs
crates/ui/src/text/markdown.rs
crates/ui/src/text/text_view.rs
crates/ui/src/theme.rs

text_view: Add syntax highlight to CodeBlock.

---

crates/story/examples/popup.rs
crates/story/src/popup_story.rs
crates/ui/src/popup_menu.rs

menu: Fix sub-menu render position.

---

crates/story/src/text_story.rs
crates/ui/src/kbd.rs
crates/ui/src/lib.rs
crates/ui/src/popup_menu.rs

kbd: Add Kdb to show keystroke.

---

crates/story/examples/text.rs
crates/story/src/text_story.rs
crates/ui/src/colors.rs
crates/ui/src/tag.rs
crates/ui/src/theme.rs

tag: Add `color` to Tag to support more colors.

---

crates/ui/src/description_list.rs
crates/ui/src/text/element.rs

description_list: Add to support border style to DescriptionList vertical layout.

---

crates/ui/src/input/input.rs
crates/ui/src/input/number_input.rs

input: Update gap between input and prefix, suffix.

---

crates/story/src/accordion_story.rs
crates/story/src/button_story.rs
crates/story/src/scrollable_story.rs
crates/ui/src/button/button.rs
crates/ui/src/button/button_group.rs

button: Improve Button to support combine outline with other variants.

---

crates/ui/src/drawer.rs
crates/ui/src/modal.rs

modal: Use bold text for Modal title.

---

crates/ui/src/dock/dock.rs
crates/ui/src/dock/tab_panel.rs

https://github.com/user-attachments/assets/c49464bf-6106-422b-b948-83c5b4c4de60
https://github.com/user-attachments/assets/b83fba18-ecfd-458f-8f25-5d59a60a66cb

dock: Fixed panels will lose height when dragged to minimum

---

Cargo.lock
crates/story/examples/tiles.rs
crates/story/src/lib.rs
crates/story/src/list_story.rs
crates/story/src/main.rs
crates/story/src/modal_story.rs
crates/story/src/table_story.rs
crates/ui/Cargo.toml
crates/ui/src/clipboard.rs
crates/ui/src/dock/mod.rs
crates/ui/src/dock/tab_panel.rs
crates/ui/src/input/blink_cursor.rs
crates/ui/src/list/list.rs
crates/ui/src/notification.rs
crates/ui/src/switch.rs
crates/ui/src/table.rs

- Update `resvg`, `usvg` to 0.45.0

chore: Update GPUI 2025/03/20 and fix spawn method.

---

crates/story/src/popup_story.rs
crates/story/src/title_bar.rs
crates/ui/src/popup_menu.rs

menu: Add label item to PopupMenu.

---

README.md
crates/story/examples/alert.rs
crates/ui/src/alert.rs
crates/ui/src/lib.rs
crates/ui/src/tab/tab.rs
crates/ui/src/tab/tab_bar.rs
crates/ui/src/theme.rs

alert: Add Alert.

---

DEVELOPMENT
rust-toolchain.toml

doc: Update Contributing Guide.

---

crates/ui/src/sidebar/menu.rs
crates/ui/src/sidebar/mod.rs

sidebar: Fix collapsed to display icon only.

---

crates/story/src/input_story.rs

Closed #741 
https://github.com/user-attachments/assets/ec572918-a574-4adb-a8c0-c59010dc4d5e

story: Sync number input value when changed

---

crates/story/examples/accordion.rs
crates/story/src/accordion_story.rs
crates/ui/src/accordion.rs

accordion: Fix toggle accordion item.

---

Cargo.lock

Reupdate because https://github.com/zed-industries/zed/issues/27767.

chore: Update GPUI 2025/03/31 2

---

crates/story/src/main.rs

example: Remove duplicate ProgressStory in main example.

---

Cargo.lock
crates/story/Cargo.toml
crates/story/src/lib.rs
crates/story/src/main.rs
crates/story/src/webview_story.rs

fixes #763
it also prevent crashing on linux due to gtk not initialized

example: Fix to hide WebView when switch tab.

---

crates/ui/src/scroll/scrollbar.rs

scrollbar: Update min thumb size to 24px.

---

crates/ui/src/input/input.rs

https://github.com/user-attachments/assets/58ff94df-3ff7-45ae-8657-a526b3ee75f7

input: Fix delete `beginning_of_line` and `end_of_line` to handle empty line.

---

crates/story/src/form_story.rs
crates/story/src/input_story.rs
crates/ui/src/input/input.rs

Closes #762
https://github.com/user-attachments/assets/068a3f11-8498-4db6-a2ac-00cc043f16cf

input: Add max_rows to support auto-grow.

---

crates/story/src/switch_story.rs
crates/ui/src/checkbox.rs

| - | - |
| <img width="672" alt="SCR-20250409-pgbg" src="https://github.com/user-attachments/assets/73a46b13-a3bb-4f58-afb0-aa388bbaefb5" /> | <img width="669" alt="SCR-20250409-phiy" src="https://github.com/user-attachments/assets/1230a02d-cdc7-4c2e-9949-bcad09eb2edc" /> |

checkbox: Support sizable

---

crates/ui/src/checkbox.rs

| - | - |
|  <img width="642" alt="SCR-20250414-nbwx" src="https://github.com/user-attachments/assets/fa3daaf8-5465-49f5-8cd5-d59c19b50494" /> | <img width="644" alt="SCR-20250414-nbli" src="https://github.com/user-attachments/assets/e45aa560-0183-460a-b76d-e3cb0203067f" /> |

checkbox: Make checked icon sizable

---

crates/story/examples/tooltip.rs
crates/story/src/lib.rs
crates/story/src/main.rs
crates/story/src/tooltip_story.rs
crates/ui/src/button/button.rs
crates/ui/src/color_picker.rs
crates/ui/src/kbd.rs
crates/ui/src/popup_menu.rs
crates/ui/src/slider.rs
crates/ui/src/tooltip.rs

- Improve `Kbd::format` method.
- Add `tooltip_with_action` method to Button for display key binding in tooltip.
- 
- The `Tooltip::new` has been changed it argument and return type.
```diff
- pub fn new(text: impl Into<Text>, _: &mut Window, cx: &mut App) -> AnyView
+ pub fn new(text: impl Into<Text>) -> Self
```

tooltip: Add KeyBinding to tooltip and Button.

---

crates/story/src/sidebar_story.rs
crates/ui/src/checkbox.rs
crates/ui/src/sidebar/menu.rs
crates/ui/src/switch.rs
crates/ui/src/theme.rs

| Light | Dark |
| - | - |
| <img width="913" alt="SCR-20250415-mkdr" src="https://github.com/user-attachments/assets/5c4931e6-4d03-48ec-91c6-ade2d86de75a" /> | <img width="913" alt="SCR-20250415-mkec" src="https://github.com/user-attachments/assets/f85af984-ecc3-4cd7-913c-c4e93384dbf1" /> |

sidebar: Add `suffix` for menu item

---

crates/story/src/main.rs
crates/ui/src/theme.rs

linux: Fix sync_system_appearance on Linux.

---

crates/story/src/main.rs
crates/ui/src/input/input.rs

gallery: Add to support search stories.

---

crates/story/src/menu_story.rs
crates/ui/src/button/button.rs
crates/ui/src/checkbox.rs
crates/ui/src/dropdown.rs
crates/ui/src/list/list_item.rs
crates/ui/src/switch.rs
crates/ui/src/tab/tab.rs
crates/ui/src/time/calendar.rs

Update disabled menu, button, dropdown etc. to use default cursor.

---

crates/story/src/modal_story.rs
crates/ui/src/modal.rs

- Fix to handle close modal when `on_ok`, `on_cancel` not present.

modal: Add alert method to create modal with a Ok button.

---

README.md

- Updated phrasing for better readability and consistency.
- Corrected grammatical errors and improved sentence structure throughout the document.

doc: Revise README for clarity and grammar improvements.

---

crates/story/src/resizable_story.rs
crates/ui/src/dock/stack_panel.rs
crates/ui/src/resizable/panel.rs

- Fix some panel resizing details.
- Fix initial_size for panel and ensure split dock panel to get average size.
https://github.com/user-attachments/assets/cd6c7e10-aec7-46a6-8a4d-11bf4d221f92
https://github.com/user-attachments/assets/90c8b865-630a-4abd-98c9-310800b12fee

resizable: Add size_range to limit panel size and fix resize and initial_size of panel.

---

Cargo.lock
crates/story/src/input_story.rs
crates/story/src/main.rs
crates/story/src/number_input_story.rs
crates/ui/Cargo.toml
crates/ui/src/input/input.rs
crates/ui/src/input/mask_pattern.rs
crates/ui/src/input/mod.rs
crates/ui/src/input/number_input.rs

- Add `mask_pattern` to Input, NumberInput.
- Fix Input `set_text` to move cursor to end.
https://github.com/user-attachments/assets/2d7e362a-3f80-47a4-94e3-efd729bffcac

input: Add mask pattern to format display.

---

crates/ui/src/input/element.rs

input: Fix selection rendering for empty lines.

---

crates/story/src/date_picker_story.rs
crates/ui/src/time/calendar.rs

calendar: support custom matcher

---

Cargo.lock

https://github.com/zed-industries/zed/pull/31022

input: Update GPUI for fix click can not to position cursor on a empty line on Windows.

---

Cargo.lock
crates/ui/src/input/state.rs

Reverts longbridge/gpui-component#874
Ref https://github.com/zed-industries/zed/pull/31031

input: Fix click can not to position cursor on empty line on Windows.

---

Cargo.lock
crates/ui/src/clipboard.rs
crates/ui/src/dock/dock.rs
crates/ui/src/input/element.rs
crates/ui/src/menu/context_menu.rs
crates/ui/src/popover.rs
crates/ui/src/resizable/panel.rs
crates/ui/src/resizable/resize_handle.rs
crates/ui/src/scroll/scrollable.rs
crates/ui/src/scroll/scrollable_mask.rs
crates/ui/src/scroll/scrollbar.rs
crates/ui/src/svg_img.rs
crates/ui/src/switch.rs
crates/ui/src/text/html.rs
crates/ui/src/text/markdown.rs
crates/ui/src/title_bar.rs
crates/ui/src/virtual_list.rs
crates/ui/src/webview.rs
crates/ui/src/window_border.rs

https://github.com/zed-industries/zed/pull/31315

chore: Upgrade GPUI 2025/05/26 with inspector changes.

---

crates/ui/src/input/state.rs

```
byte index 3 is not a char boundary; it is inside '吧' (bytes 1..4) of `L吧2`:    0: <unknown>
```

input: Fix Input may out of char boundary 

---

crates/story/src/button_story.rs
crates/ui/src/button/button.rs
crates/ui/src/button/dropdown_button.rs
crates/ui/src/checkbox.rs
crates/ui/src/list/list_item.rs
crates/ui/src/popover.rs
crates/ui/src/sidebar/footer.rs
crates/ui/src/sidebar/header.rs
crates/ui/src/styled.rs
crates/ui/src/tab/tab.rs

- Add `is_selected` to the `Selectable` trait; Returns true if the element is selected.

button: Impl `Selectable` for the dropdown button

---

crates/ui/src/menu/popup_menu.rs

popup_menu: Do not dismiss PopupMenu when clicked on a submenu item.

---

crates/story/src/tag_story.rs
crates/ui/src/tag.rs

tag: Add `rounded` to Tag and support `outline` for all variants.

---

crates/ui/src/highlighter/languages.rs
crates/ui/src/highlighter/languages/zig/highlights.scm
crates/ui/src/highlighter/languages/zig/injections.scm

highlighter: Fix Zig language highlight.

---

Cargo.lock
crates/ui/src/list/list.rs
crates/ui/src/table.rs

close #943
I am not sure about title specification of PR. pls feel free to edit.

chore: Update GPUI and fix uniform_list API changes.

---

crates/story/examples/code-editor.rs
crates/ui/src/highlighter/highlighter.rs
crates/ui/src/highlighter/languages.rs

Close #952 
Fallback to use plain text to display.

highlighter: Avoid crash when language not registered.

---

crates/ui/src/list/list.rs
crates/ui/src/table.rs

list: Add a default style for empty data

---

crates/ui/src/input/blink_cursor.rs

https://github.com/user-attachments/assets/3b7d2cfd-50b0-4744-bb74-1deafc5710e3

input: Keep showing the blink cursor when typing or moving.

---

crates/ui/src/input/element.rs
crates/ui/src/input/hover_popover.rs
crates/ui/src/input/state.rs

Close #908
https://github.com/user-attachments/assets/f050dd1a-501c-4784-a45b-78ba77cdf19c

input: Fix move up/down to keep same column.

---

README.md
crates/webview/README.md
crates/webview/examples/wef-example/build.rs
crates/wef/README.md

wef: Fix doc and warnings.

---

crates/ui/src/menu/popup_menu.rs

|--| -- |
| <img width="166" alt="image" src="https://github.com/user-attachments/assets/883eb78b-9ea3-4f1b-b01e-81fbbbdd39ed" /> | <img width="166" alt="image" src="https://github.com/user-attachments/assets/9ba551aa-5d9e-49ed-adfa-3da6c654f0c4" />|
Ref #979 but not fix.

menu: Fix scrollbar can't drag to bottom of scrollable PopupMenu.

---

crates/macros/src/derive_into_plot.rs
crates/story/src/label_story.rs
crates/ui/src/time/calendar.rs

**_Masked_** was incorrectly spelled in the file label_story.rs

chore: Fix spelling of the word masked

---

crates/ui/src/button/button.rs
crates/ui/src/button/dropdown_button.rs

dropdown_button: Keep rounded when is a ghost variant.

---

crates/story/src/title_bar.rs
crates/ui/src/checkbox.rs
crates/ui/src/modal.rs
crates/ui/src/notification.rs
crates/ui/src/radio.rs
crates/ui/src/theme.rs

To match shadcn/ui recently update.

theme: Update default radius to 6px, and modal to 8px.

---

crates/ui/src/input/element.rs

Close #997 
https://github.com/user-attachments/assets/6ad9f431-b5a2-42f1-93e6-6425f0851898

input: Fix wrap text not draw in multi-line mode.

---

crates/story/src/badge_story.rs
crates/story/src/dropdown_story.rs
crates/ui/src/alert.rs
crates/ui/src/badge.rs
crates/ui/src/breadcrumb.rs
crates/ui/src/button/button.rs
crates/ui/src/button/button_group.rs
crates/ui/src/button/dropdown_button.rs
crates/ui/src/button/toggle.rs
crates/ui/src/checkbox.rs
crates/ui/src/color_picker.rs
crates/ui/src/divider.rs
crates/ui/src/dropdown.rs
crates/ui/src/kbd.rs
crates/ui/src/label.rs
crates/ui/src/link.rs
crates/ui/src/notification.rs
crates/ui/src/radio.rs
crates/ui/src/skeleton.rs
crates/ui/src/switch.rs
crates/ui/src/tag.rs
crates/ui/src/tooltip.rs

This PR for continuing #1005 was missed commits.

chore: Impl `Styled` for more elements.

---

Cargo.lock
crates/story/examples/description_list.rs
crates/story/examples/dock.rs
crates/story/examples/tiles.rs
crates/story/src/button_story.rs
crates/story/src/drawer_story.rs
crates/story/src/dropdown_story.rs
crates/story/src/form_story.rs
crates/story/src/input_story.rs
crates/story/src/lib.rs
crates/story/src/list_story.rs
crates/story/src/menu_story.rs
crates/story/src/modal_story.rs
crates/story/src/number_input_story.rs
crates/story/src/otp_input_story.rs
crates/story/src/popover_story.rs
crates/story/src/sidebar_story.rs
crates/story/src/table_story.rs
crates/story/src/textarea_story.rs
crates/story/src/toggle_story.rs
crates/story/src/tooltip_story.rs
crates/ui/src/actions.rs
crates/ui/src/input/state.rs
crates/ui/src/tab/tab_bar.rs
crates/webview/src/context_menu.rs

Ref https://github.com/zed-industries/zed/pull/33263

chore: Upgrade GPUI and fix action API changes.

---

crates/story/src/icon_story.rs
crates/ui/src/button/toggle.rs
crates/ui/src/checkbox.rs
crates/ui/src/color_picker.rs
crates/ui/src/highlighter/registry.rs
crates/ui/src/input/hover_popover.rs
crates/ui/src/input/otp_input.rs
crates/ui/src/radio.rs
crates/ui/src/styled.rs
crates/ui/src/tab/tab.rs
crates/ui/src/theme.rs

This PR for fix https://github.com/longbridge/gpui-component/pull/1009 mistake.

chore: Move `shadow_xs` to `StyledExt` trait.

---

crates/ui/src/button/dropdown_button.rs

| - | - |
| <img width="218" alt="SCR-20250625-psed" src="https://github.com/user-attachments/assets/873db4e9-d169-4273-bee9-58332b41c00f" /> | <img width="222" alt="SCR-20250625-prxz" src="https://github.com/user-attachments/assets/48f8cb35-cd67-47ac-bbb9-2739e1aa16b9" /> |

dropdown_button: Fix incorrect rounded when ghost button selected

---

crates/ui/src/form.rs

form: Fix form label required not in same line.

---

crates/story/examples/html.html
crates/ui/src/text/element.rs
crates/ui/src/text/html.rs

text_view: Fix `li > strong` render not in same line.

---

DEVELOPMENT.md

Some minor grammatical updates to the Development Guide.

chore: Minor updates on the wording of DEVELOPMENT.md

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
crates/ui/Cargo.toml
crates/ui/src/event.rs
crates/ui/src/menu/context_menu.rs
crates/webview/Cargo.toml

Close #1024 
Ref https://github.com/zed-industries/zed/pull/32436

chore: Update GPUI and fix `FocusableWrapper` removed error.

---

crates/ui/src/text/element.rs

text_view: Fix list item text wrap.

---

crates/story/src/form_story.rs
crates/ui/src/form.rs

| - | - |
| <img width="752" alt="image" src="https://github.com/user-attachments/assets/32abd11a-39c6-4045-9727-3188c46e482c" /> | <img width="752" alt="image" src="https://github.com/user-attachments/assets/98e45484-1c05-4d90-977f-efd9b89d9dd9" /> |

form: Fix label text wrapping issue

---

crates/ui/src/text/element.rs
crates/ui/src/text/html.rs
crates/ui/src/text/markdown.rs

text_view: Fix list item to merge inline paragraphs, and fix paragraphs margin.

---

Cargo.lock
crates/ui/src/input/hover_popover.rs
crates/ui/src/input/otp_input.rs
crates/ui/src/styled.rs

https://github.com/zed-industries/zed/pull/33361

chore: Remove `shadow_xs`, now GPUI has this method.

---

crates/story/src/alert_story.rs
crates/story/src/main.rs
crates/ui/src/alert.rs
crates/ui/src/text/text_view.rs

alert: Improve Alert styles.

---

crates/story/src/date_picker_story.rs
crates/story/src/dropdown_story.rs
crates/story/src/form_story.rs
crates/story/src/input_story.rs
crates/story/src/number_input_story.rs
crates/ui/src/dropdown.rs
crates/ui/src/input/number_input.rs
crates/ui/src/input/text_input.rs
crates/ui/src/time/date_picker.rs

input: Add appearance option to NumberInput, Dropdown, DatePicker to render without style.

---

crates/story/src/label_story.rs
crates/ui/src/label.rs

label: Add support for highlighting specified text

---

Cargo.lock
crates/ui/src/modal.rs

This PR adds a fade in animation for modals, which makes the UI looks smoother.
https://github.com/user-attachments/assets/7671aa78-a3bd-43a6-ace7-d051d24f2523

modal: Refine enter animation

---

crates/ui/src/switch.rs

Ref https://github.com/zed-industries/zed/pull/34741
Now `Switch` can use impl RenderOnce.

switch: Apply `use_keyed_state` to store toggle state for animation.

---

crates/ui/src/scroll/scrollbar.rs

The current scrollbar implementation calls `Window::request_animation_frame` during the delay phase, which causes unnecessary CPU usage. This PR updates the scrollbar to use a timer to wait before starting the fade-out animation, allowing the CPU to remain idle during this phase.
There is the comparison with Instruments.
**Before:**
**After:**

scrollbar: Reduce unnecessary frame updates

---

crates/ui/src/table/mod.rs

| - | - |
| <img width="355" height="165" alt="SCR-20250801-kaof" src="https://github.com/user-attachments/assets/ac073913-7813-43f2-a860-690a2366640b" /> <img width="268" height="137" alt="SCR-20250801-kgqk" src="https://github.com/user-attachments/assets/6a01df6d-fbf9-42a3-bfa3-4120a28b1401" /> |  <img width="378" height="176" alt="SCR-20250801-kags" src="https://github.com/user-attachments/assets/c5a3196d-4d0f-469b-b0d4-ce60b8dbe3f1" /> <img width="274" height="136" alt="SCR-20250801-kgik" src="https://github.com/user-attachments/assets/649ff866-f153-40f3-97fa-7715f7480a2f" /> |

table: Fix the border overlap issue

---

crates/story/src/virtual_list_story.rs
crates/ui/src/list/list.rs
crates/ui/src/scroll/scrollbar.rs

https://github.com/user-attachments/assets/823f3ac7-4335-4dae-a540-a2ccd11b8fc8

scrollbar: Show scrollbar immediately when scroll offset changed.

---

Cargo.lock
crates/ui/src/event.rs

chore: Update GPUI to fix click_count API changes.

---

crates/story/src/dropdown_story.rs
crates/ui/src/dropdown.rs
crates/ui/src/list/list.rs
crates/ui/src/virtual_list.rs

- Fixed List scroll to item at first time rendering.

virtual_list: Fix scroll to item not align to paddings.

---

crates/story/src/menu_story.rs
crates/ui/src/menu/popup_menu.rs
crates/ui/src/virtual_list.rs

- Fix scrollbar position in popup menu.

virtual_list: Avoid scroll when list contents not overflow.

---

Cargo.lock
crates/ui/src/theme/schema.rs
themes/adventure.json
themes/ayu.json
themes/catppuccin.json
themes/default.json
themes/everforest.json
themes/fahrenheit.json
themes/flexoki.json
themes/gruvbox.json
themes/harper.json
themes/hybrid.json
themes/jellybeans.json
themes/macos-classic.json
themes/mellifluous.json
themes/molokai.json
themes/solarized.json
themes/spaceduck.json
themes/tokyonight.json
themes/twilight.json

Also updated the themes colors to match this default rule.

theme: Improve theme color fallback to use blend to avoid alpha.

---

crates/ui/src/table/mod.rs

table: Refine the row style

---

Cargo.lock

https://github.com/zed-industries/zed/pull/36663

chore: Update GPUI to solve SVG rendering size.

---

crates/story/src/themes.rs
crates/ui/src/theme/mod.rs

And fix theme menu selected item in example when theme mode changed.

theme: Add `theme_name` to get current active theme name.

---

crates/ui/src/highlighter/highlighter.rs

This PR just removed the partial update highlight cache code. This logic will get incorrect offset.
To make sure highlight correct first.
Remove this will slow down performance (On editing), when is more than 5K lines, but if less than this the performance can accept.

highlighter: Fix some editing operatons might result incorrect hightlight.

---

crates/ui/src/inspector.rs

This PR aims to fix a bug of the Rust parser in my last PR #1205.

inspector: Fix Rust parser of inspector.

---

crates/ui/src/input/blink_cursor.rs
crates/ui/src/input/state.rs

https://github.com/user-attachments/assets/751d0b62-18f9-41c8-80a0-e11439e3b91e

input: Pause blink and keep show cursor on moving or editing.

---

crates/ui/src/input/element.rs

input: Fix horizontal scroll to match the longest line width.

---

crates/story/src/form_story.rs
crates/ui/src/form.rs

| Vertical | Horizontal |
| - | - |
| <img width="1642" height="1106" alt="SCR-20250916-nnry" src="https://github.com/user-attachments/assets/279eb192-c660-449e-931e-1d7ff79ac69f" /> | <img width="1642" height="1106" alt="image" src="https://github.com/user-attachments/assets/289a6672-d82d-4f6f-a267-592874ccbe42" /> |

form: Add support for multi-column layout

---

crates/story/src/form_story.rs
crates/ui/src/form.rs

* Continue https://github.com/longbridge/gpui-component/pull/1250

form: Add `col_start` and `col_end` for the fields

---

crates/story/examples/code-editor.rs
crates/ui/src/input/element.rs
crates/ui/src/input/lsp.rs
crates/ui/src/input/popovers/completion_menu.rs
crates/ui/src/input/popovers/diagnostic_popover.rs
crates/ui/src/input/popovers/hover_popover.rs
crates/ui/src/input/popovers/mod.rs
crates/ui/src/input/rope_ext.rs
crates/ui/src/input/state.rs

editor: Add to support HoverPopover.

---

.github/workflows/ci.yml
crates/story/examples/editor.rs
crates/ui/src/input/lsp/completions.rs
crates/ui/src/input/popovers/completion_menu.rs

And to support `filter_text` as completion item highlight match.

editor: Change to pass cursor as `offset` for `completions` method.

---

crates/ui/src/highlighter/diagnostics.rs
crates/ui/src/input/popovers/completion_menu.rs
crates/ui/src/input/rope_ext.rs
crates/ui/src/inspector.rs

inspector: Add to support auto complete.

---

Cargo.lock
crates/ui/src/actions.rs
crates/ui/src/input/search.rs
crates/ui/src/menu/context_menu.rs
crates/ui/src/menu/menu_item.rs
crates/ui/src/menu/popup_menu.rs

- And add to support scroll to selected item.

menu: Fix to support keyboard to select menu items.

---

crates/story/examples/editor.rs
crates/ui/src/highlighter/highlighter.rs
crates/ui/src/highlighter/mod.rs
crates/ui/src/highlighter/registry.rs
crates/ui/src/input/element.rs
crates/ui/src/input/mode.rs
crates/ui/src/lib.rs
crates/ui/src/text/format/html.rs
crates/ui/src/text/format/markdown.rs
crates/ui/src/text/inline.rs
crates/ui/src/text/node.rs
crates/ui/src/text/style.rs
crates/ui/src/text/text_view.rs

1. Parse content in the background thread  
2. Remove unnecessary clones  
3. `TextViewStyle` and `LanguageRegistry` can now be used across threads

text_view: Refactor TextView, SyntaxHighlighter to use async to parsing.

---

crates/ui/src/input/state.rs

Now we can handle about 1M lines.
https://github.com/user-attachments/assets/cb55cd18-6755-40cd-a5b0-3d0f865d12e1

editor: Input enter to get next indent level performance.

---

crates/ui/src/highlighter/highlighter.rs

SyntaxHighlighter panics when highlighting text containing multi-byte UTF-8 characters (Chinese, Japanese, emoji, etc).
**Error**: `thread 'main' panicked at ropey-2.0.0-beta.1/src/rope.rs:694:59`
**Root Cause**: tree-sitter may return byte offsets that fall in the middle of multi-byte UTF-8 characters. When `Rope::slice()` receives such offsets, it checks `is_char_boundary()` and panics with `NonCharBoundary` error.
Use `RopeExt::clip_offset()` to adjust byte offsets to the nearest char boundaries before calling `slice()`.
**Changes**:
- Line 395-398: Clip offsets in main highlighting loop
- Line 441-443: Clip offsets when extracting injection content  
- Line 478-479: Added explanatory comment for injection highlighting
- Added imports for `RopeExt` and `Bias`
**Safety**:
- `Bias::Left` …

highlighter: Use clip_offset to ensure UTF-8 char boundaries

---

Cargo.lock
crates/story/Cargo.toml
crates/story/examples/editor.rs
crates/story/examples/fixtures/test.json
crates/story/examples/fixtures/test.rs
crates/ui/src/input/element.rs
crates/ui/src/input/lsp/document_colors.rs
crates/ui/src/input/lsp/mod.rs
crates/ui/src/input/state.rs
crates/ui/src/input/text_input.rs
crates/ui/src/theme/mod.rs

editor: Add document_colors LSP.
